'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import MemberShell from '@/components/member-shell'
import { supabase } from '@/lib/browser-supabase'
import {useI18n} from '@/components/i18n'

type Item={id:string;opportunity_id:string|null;stage:string;quoted_value:number|null;deal_value:number|null;currency:string;verified:boolean;notes:string|null;next_action:string|null;opportunities?:{title:string;buyer:string;region:string;closing_date:string|null}|null}
const stages=['New','Interested','Contacted','Quoted','Won','Lost']
const copy={
 en:{eyebrow:'MY OPPORTUNITIES',title:'Saved Opportunities',sub:'Keep the opportunities you care about in one place and record what happened next.',find:'Find opportunities',saved:'Saved',submitted:'Submitted / quoted',won:'Won',value:'Recorded won value',loading:'Loading saved opportunities…',empty:'No saved opportunities yet',emptyText:'Open an opportunity and choose Save Opportunity when you want to keep following it.',browse:'Browse opportunities',fallback:'Saved opportunity',closing:'closes',progress:'Progress',quoted:'Quoted value',wonValue:'Won value',next:'Next step',nextPh:'Check documents / call buyer',open:'Open',remove:'Remove',labels:{New:'Saved',Interested:'Considering',Contacted:'Contacted',Quoted:'Submitted / Quoted',Won:'Won',Lost:'Not Won'}},
 zh:{eyebrow:'我的商机',title:'已保存商机',sub:'把你想继续关注的商机集中在这里，并记录后续进度和结果。',find:'寻找商机',saved:'已保存',submitted:'已提交／已报价',won:'已赢得',value:'记录的赢标金额',loading:'正在加载已保存商机…',empty:'还没有保存任何商机',emptyText:'打开商机后，如果想继续关注，就选择“保存商机”。',browse:'浏览商机',fallback:'已保存商机',closing:'截止',progress:'进度',quoted:'报价金额',wonValue:'赢标金额',next:'下一步',nextPh:'检查文件／联系采购方',open:'打开',remove:'移除',labels:{New:'已保存',Interested:'考虑中',Contacted:'已联系',Quoted:'已提交／已报价',Won:'已赢得',Lost:'未赢得'}},
 ms:{eyebrow:'PELUANG SAYA',title:'Peluang Disimpan',sub:'Simpan peluang yang penting di satu tempat dan rekodkan apa yang berlaku seterusnya.',find:'Cari peluang',saved:'Disimpan',submitted:'Dihantar / disebut harga',won:'Menang',value:'Nilai kemenangan direkodkan',loading:'Memuatkan peluang disimpan…',empty:'Belum ada peluang disimpan',emptyText:'Buka peluang dan pilih Simpan Peluang apabila anda mahu terus mengikutinya.',browse:'Lihat peluang',fallback:'Peluang disimpan',closing:'tutup',progress:'Kemajuan',quoted:'Nilai sebut harga',wonValue:'Nilai menang',next:'Langkah seterusnya',nextPh:'Semak dokumen / hubungi pembeli',open:'Buka',remove:'Buang',labels:{New:'Disimpan',Interested:'Dipertimbangkan',Contacted:'Dihubungi',Quoted:'Dihantar / disebut harga',Won:'Menang',Lost:'Tidak menang'}}
} as const

export default function PipelinePage(){
  const {lang}=useI18n();const c=copy[lang]
  const [items,setItems]=useState<Item[]>([]);const [loading,setLoading]=useState(true)
  async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data}=await supabase.from('pipeline_items').select('*,opportunities(title,buyer,region,closing_date)').eq('user_id',user.id).order('updated_at',{ascending:false});setItems((data as Item[]|null)??[]);setLoading(false)}
  useEffect(()=>{load()},[])
  async function update(id:string,patch:Partial<Item>){await supabase.from('pipeline_items').update(patch).eq('id',id);setItems(v=>v.map(x=>x.id===id?{...x,...patch}:x))}
  async function remove(id:string){await supabase.from('pipeline_items').delete().eq('id',id);setItems(v=>v.filter(x=>x.id!==id))}
  const wonValue=items.filter(x=>x.stage==='Won').reduce((s,x)=>s+Number(x.deal_value??0),0)
  return <MemberShell><main className="member-page"><div className="container"><div className="member-heading"><div><div className="eyebrow">{c.eyebrow}</div><h1 className="page-title">{c.title}</h1><p className="sub">{c.sub}</p></div><Link className="btn primary" href="/opportunities">{c.find}</Link></div><div className="kpis member-kpis"><div className="kpi"><strong>{items.length}</strong><span>{c.saved}</span></div><div className="kpi"><strong>{items.filter(x=>x.stage==='Quoted').length}</strong><span>{c.submitted}</span></div><div className="kpi"><strong>{items.filter(x=>x.stage==='Won').length}</strong><span>{c.won}</span></div><div className="kpi"><strong>RM{wonValue.toLocaleString()}</strong><span>{c.value}</span></div></div>{loading?<div className="panel">{c.loading}</div>:items.length===0?<div className="empty-state"><h2>{c.empty}</h2><p>{c.emptyText}</p><Link className="btn primary" href="/opportunities">{c.browse}</Link></div>:<div className="pipeline-board">{stages.map(stage=><section className="pipeline-column" key={stage}><div className="pipeline-column-head"><b>{c.labels[stage as keyof typeof c.labels]}</b><span>{items.filter(x=>x.stage===stage).length}</span></div>{items.filter(x=>x.stage===stage).map(item=><article className="pipeline-card" key={item.id}><div className="pipeline-title">{item.opportunities?.title??c.fallback}</div><div className="meta">{item.opportunities?.buyer??'—'}<br/>{item.opportunities?.region??''}{item.opportunities?.closing_date?` · ${c.closing} ${item.opportunities.closing_date}`:''}</div><label className="mini-label">{c.progress}<select value={item.stage} onChange={e=>update(item.id,{stage:e.target.value})}>{stages.map(x=><option key={x} value={x}>{c.labels[x as keyof typeof c.labels]}</option>)}</select></label>{item.stage==='Quoted'&&<label className="mini-label">{c.quoted}<input type="number" value={item.quoted_value??''} onChange={e=>update(item.id,{quoted_value:e.target.value?Number(e.target.value):null})}/></label>}{item.stage==='Won'&&<label className="mini-label">{c.wonValue}<input type="number" value={item.deal_value??''} onChange={e=>update(item.id,{deal_value:e.target.value?Number(e.target.value):null})}/></label>}<label className="mini-label">{c.next}<input value={item.next_action??''} onChange={e=>setItems(v=>v.map(x=>x.id===item.id?{...x,next_action:e.target.value}:x))} onBlur={e=>update(item.id,{next_action:e.target.value||null})} placeholder={c.nextPh}/></label><div className="card-actions">{item.opportunity_id&&<Link className="source" href={`/opportunities/${item.opportunity_id}`}>{c.open}</Link>}<button className="link-danger" onClick={()=>remove(item.id)}>{c.remove}</button></div></article>)}</section>)}</div>}</div></main></MemberShell>
}
