'use client'

import { useEffect, useState } from 'react'
import MemberShell from '@/components/member-shell'
import { supabase } from '@/lib/browser-supabase'
import {useI18n} from '@/components/i18n'

const capabilityOptions = ['AV Integration','Broadcast','LED','Audio','Camera','Streaming','Event Production','IT','CCTV','Digital Signage','Communications','Construction','Facilities','Automotive','Healthcare']
const marketOptions = ['Sarawak','Sabah','Brunei','Kalimantan']
const lookingOptions = ['Customers','Tenders','Projects','Partners','Dealers','Suppliers','Distributors']
const lookingLabels={en:{Customers:'Customers',Tenders:'Tenders',Projects:'Projects',Partners:'Partners',Dealers:'Dealers',Suppliers:'Suppliers',Distributors:'Distributors'},zh:{Customers:'客户',Tenders:'标案',Projects:'项目',Partners:'合作伙伴',Dealers:'经销商',Suppliers:'供应商',Distributors:'分销商'},ms:{Customers:'Pelanggan',Tenders:'Tender',Projects:'Projek',Partners:'Rakan niaga',Dealers:'Pengedar',Suppliers:'Pembekal',Distributors:'Distributor'}} as const

type Company = { id:string; name:string; region:string; website:string|null; description:string|null; capabilities:string[]; brands:string[]; markets:string[]; opportunity_markets:string[]; looking_for:string[]; is_verified:boolean }
const copy={
 en:{eyebrow:'Company profile',title:'Company Profile',sub:'Your company base, delivery markets and opportunity markets are separate so you can look for business across Borneo.',verified:'Verified company',loading:'Loading company profile…',identity:'Identity',name:'Your name',company:'Company name',base:'Company base',website:'Website',description:'Company description',descriptionPh:'What does your company actually do?',brands:'Brands represented / supplied',capabilities:'Capabilities',capHelp:'Select what your company can actually deliver.',served:'Markets served',servedHelp:'Where your company can deliver work.',opp:'Opportunity markets',oppHelp:'Choose one or more Borneo markets where you want to find opportunities.',looking:'Looking for',save:'Save Company Profile',saving:'Saving…',needMarket:'Choose at least one opportunity market.',session:'Your session needs to be refreshed. Please sign in again.',unable:'Unable to save',saved:'Profile saved. Your company settings are now active.'},
 zh:{eyebrow:'公司资料',title:'公司资料',sub:'公司所在地、实际服务市场和想寻找商机的市场可以分别设置。',verified:'已验证公司',loading:'正在加载公司资料…',identity:'基本资料',name:'你的姓名',company:'公司名称',base:'公司所在地',website:'公司网站',description:'公司简介',descriptionPh:'你的公司实际上提供什么产品或服务？',brands:'代理／供应品牌',capabilities:'公司能力',capHelp:'只选择公司实际上可以交付的能力。',served:'服务市场',servedHelp:'公司实际可以交付项目的地区。',opp:'商机市场',oppHelp:'选择一个或多个你想寻找商机的婆罗洲市场。',looking:'目前想找',save:'保存公司资料',saving:'正在保存…',needMarket:'请至少选择一个商机市场。',session:'登录状态需要更新，请重新登录。',unable:'无法保存',saved:'公司资料已保存，新设置已经生效。'},
 ms:{eyebrow:'Profil syarikat',title:'Profil Syarikat',sub:'Lokasi syarikat, pasaran perkhidmatan dan pasaran peluang boleh ditetapkan secara berasingan.',verified:'Syarikat disahkan',loading:'Memuatkan profil syarikat…',identity:'Maklumat asas',name:'Nama anda',company:'Nama syarikat',base:'Lokasi syarikat',website:'Laman web',description:'Penerangan syarikat',descriptionPh:'Apakah produk atau perkhidmatan sebenar syarikat anda?',brands:'Jenama diwakili / dibekalkan',capabilities:'Keupayaan',capHelp:'Pilih hanya keupayaan yang benar-benar boleh disediakan oleh syarikat.',served:'Pasaran dilayani',servedHelp:'Tempat syarikat boleh melaksanakan kerja.',opp:'Pasaran peluang',oppHelp:'Pilih satu atau lebih pasaran Borneo untuk mencari peluang.',looking:'Sedang mencari',save:'Simpan Profil Syarikat',saving:'Menyimpan…',needMarket:'Pilih sekurang-kurangnya satu pasaran peluang.',session:'Sesi anda perlu diperbaharui. Sila log masuk semula.',unable:'Tidak dapat disimpan',saved:'Profil disimpan. Tetapan syarikat anda kini aktif.'}
} as const

export default function ProfilePage(){
  const {lang}=useI18n();const c=copy[lang]
  const [company,setCompany]=useState<Company|null>(null);const [fullName,setFullName]=useState('');const [message,setMessage]=useState('');const [saving,setSaving]=useState(false)
  useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser(); if(!user)return;const [{data:p},{data:co}]=await Promise.all([supabase.from('profiles').select('full_name').eq('id',user.id).maybeSingle(),supabase.from('companies').select('*').eq('owner_id',user.id).order('created_at',{ascending:true}).limit(1).maybeSingle()]);setFullName(p?.full_name ?? '');const loaded=co as Company|null;setCompany(loaded ? {...loaded, opportunity_markets:loaded.opportunity_markets?.length?loaded.opportunity_markets:(loaded.markets?.length?loaded.markets:[loaded.region])} : {id:'',name:'',region:'Sarawak',website:null,description:null,capabilities:[],brands:[],markets:['Sarawak'],opportunity_markets:['Sarawak'],looking_for:['Tenders','Projects'],is_verified:false})})()},[])
  function toggle(field:'capabilities'|'markets'|'opportunity_markets'|'looking_for',value:string){if(!company)return;setCompany({...company,[field]:company[field].includes(value)?company[field].filter(x=>x!==value):[...company[field],value]})}
  function set<K extends keyof Company>(key:K,value:Company[K]){if(company)setCompany({...company,[key]:value})}
  async function save(e:React.FormEvent){e.preventDefault();if(!company)return;if(company.opportunity_markets.length===0){setMessage(c.needMarket);return}setSaving(true);setMessage(c.saving);const {data:{user}}=await supabase.auth.getUser();if(!user){setMessage(c.session);setSaving(false);return}const profileResult=await supabase.from('profiles').upsert({id:user.id,full_name:fullName});const payload={owner_id:user.id,name:company.name,region:company.region,website:company.website||null,description:company.description||null,capabilities:company.capabilities,brands:company.brands,markets:company.markets,opportunity_markets:company.opportunity_markets,looking_for:company.looking_for};const companyResult=company.id?await supabase.from('companies').update(payload).eq('id',company.id).select('*').single():await supabase.from('companies').insert(payload).select('*').single();if(profileResult.error||companyResult.error){setMessage(profileResult.error?.message||companyResult.error?.message||c.unable);setSaving(false);return}setCompany(companyResult.data as Company);setMessage(c.saved);setSaving(false)}
  return <MemberShell><main className="member-page"><div className="container narrow-wide"><div className="member-heading"><div><div className="eyebrow">{c.eyebrow}</div><h1 className="page-title">{c.title}</h1><p className="sub">{c.sub}</p></div>{company?.is_verified&&<span className="verified-badge">{c.verified}</span>}</div>{!company?<div className="panel">{c.loading}</div>:<form className="profile-form" onSubmit={save}><section className="panel"><div className="panel-title">{c.identity}</div><div className="form-grid"><label>{c.name}<input value={fullName} onChange={e=>setFullName(e.target.value)} required/></label><label>{c.company}<input value={company.name} onChange={e=>set('name',e.target.value)} required/></label><label>{c.base}<select value={company.region} onChange={e=>set('region',e.target.value)}>{marketOptions.map(x=><option key={x}>{x}</option>)}</select></label><label>{c.website}<input value={company.website??''} onChange={e=>set('website',e.target.value)} placeholder="https://"/></label></div><label>{c.description}<textarea value={company.description??''} onChange={e=>set('description',e.target.value)} rows={4} placeholder={c.descriptionPh}/></label><label>{c.brands}<input value={company.brands.join(', ')} onChange={e=>set('brands',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))} placeholder="Sony, Blackmagic Design, Shure…"/></label></section><section className="panel"><div className="panel-title">{c.capabilities}</div><p className="meta">{c.capHelp}</p><div className="choice-grid">{capabilityOptions.map(x=><button type="button" key={x} className={`choice ${company.capabilities.includes(x)?'selected':''}`} onClick={()=>toggle('capabilities',x)}>{x}</button>)}</div></section><section className="panel"><div className="panel-title">{c.served}</div><p className="meta">{c.servedHelp}</p><div className="choice-grid small-grid">{marketOptions.map(x=><button type="button" key={x} className={`choice ${company.markets.includes(x)?'selected':''}`} onClick={()=>toggle('markets',x)}>{x}</button>)}</div></section><section className="panel"><div className="panel-title">{c.opp}</div><p className="meta">{c.oppHelp}</p><div className="choice-grid small-grid">{marketOptions.map(x=><button type="button" key={x} className={`choice ${company.opportunity_markets.includes(x)?'selected':''}`} onClick={()=>toggle('opportunity_markets',x)}>{x}</button>)}</div></section><section className="panel"><div className="panel-title">{c.looking}</div><div className="choice-grid">{lookingOptions.map(x=><button type="button" key={x} className={`choice ${company.looking_for.includes(x)?'selected':''}`} onClick={()=>toggle('looking_for',x)}>{lookingLabels[lang][x as keyof typeof lookingLabels.en]}</button>)}</div></section><div className="save-bar"><span className="meta">{message}</span><button className="btn primary" disabled={saving}>{saving?c.saving:c.save}</button></div></form>}</div></main></MemberShell>
}
