'use client'

import Link from 'next/link'
import {useI18n} from '@/components/i18n'
import type {OpportunityAward} from '@/lib/data'

type Company={canonical_name:string}
function money(value:number|null,currency:string,lang:'en'|'zh'|'ms'){if(value==null)return lang==='zh'?'未公开':lang==='ms'?'Tidak didedahkan':'Not disclosed';try{return new Intl.NumberFormat('en-MY',{style:'currency',currency,maximumFractionDigits:2}).format(value)}catch{return `${currency} ${value.toLocaleString()}`}}
const copy={
 en:{back:'← Back to opportunities',eyebrow:'PUBLIC AWARD HISTORY · SARAWAK',lead:'Observed public procurement award history collected from official sources. This is a public-data record, not a claimed or verified company-owned profile.',source:'Source-backed company history',sourceText:'Each record below comes from an official published award/result page. Coverage depends on the public sources currently indexed by Borneo Business and is not a complete legal or financial company history.',observed:'Observed awards',tender:'Tender awards',quotation:'Quotation awards',buyers:'Observed buyers',value:'Value disclosed',market:'Market',notDisclosed:'Not disclosed in indexed sources',history:'Award history',date:'Date',project:'Project / award',buyer:'Buyer',type:'Type',amount:'Value',record:'Award record',official:'Official result',empty:'No indexed award history is available for this company yet.'},
 zh:{back:'← 返回商机',eyebrow:'公开中标记录 · 砂拉越',lead:'根据官方公开来源整理的采购中标记录。这是公开资料记录，不代表该公司自行认领或已验证的企业主页。',source:'有来源的公司中标记录',sourceText:'以下每一笔资料都来自官方公布的中标／结果页面。覆盖范围取决于 Borneo Business 当前已收录的公开来源，并不代表完整的法律或财务历史。',observed:'观察到的中标记录',tender:'Tender 中标',quotation:'Quotation 中标',buyers:'观察到的采购方',value:'已公开金额',market:'市场',notDisclosed:'已收录来源未公开金额',history:'中标历史',date:'日期',project:'项目／中标记录',buyer:'采购方',type:'类型',amount:'金额',record:'中标记录',official:'官方结果',empty:'目前还没有这个公司的已收录中标历史。'},
 ms:{back:'← Kembali ke peluang',eyebrow:'SEJARAH ANUGERAH AWAM · SARAWAK',lead:'Sejarah anugerah perolehan awam yang diperhatikan daripada sumber rasmi. Ini ialah rekod data awam, bukan profil milik syarikat yang dituntut atau disahkan.',source:'Sejarah syarikat bersumber rasmi',sourceText:'Setiap rekod di bawah datang daripada halaman anugerah/keputusan rasmi yang diterbitkan. Liputan bergantung pada sumber awam yang kini diindeks oleh Borneo Business dan bukan sejarah undang-undang atau kewangan syarikat yang lengkap.',observed:'Anugerah diperhatikan',tender:'Anugerah tender',quotation:'Anugerah sebut harga',buyers:'Pembeli diperhatikan',value:'Nilai didedahkan',market:'Pasaran',notDisclosed:'Tidak didedahkan dalam sumber diindeks',history:'Sejarah anugerah',date:'Tarikh',project:'Projek / anugerah',buyer:'Pembeli',type:'Jenis',amount:'Nilai',record:'Rekod anugerah',official:'Keputusan rasmi',empty:'Belum ada sejarah anugerah diindeks untuk syarikat ini.'}
} as const

export default function AwardCompanyView({company,history}:{company:Company;history:OpportunityAward[]}){const {lang}=useI18n();const c=copy[lang];const tenderCount=history.filter(x=>x.procurement_type==='Tender').length;const quotationCount=history.filter(x=>x.procurement_type==='Quotation').length;const buyers=new Set(history.map(x=>x.buyer).filter(Boolean));const disclosed=history.filter(x=>x.awarded_value!=null);const total=disclosed.reduce((s,x)=>s+(x.awarded_value??0),0);return <main className="section"><div className="container policy-container"><Link className="source back-link" href="/opportunities">{c.back}</Link><div className="eyebrow">{c.eyebrow}</div><h1 className="detail-title">{company.canonical_name}</h1><p className="lead">{c.lead}</p><div className="source-trust-note"><strong>{c.source}</strong><span>{c.sourceText}</span></div><div className="detail-grid panel"><div><span>{c.observed}</span><strong>{history.length}</strong></div><div><span>{c.tender}</span><strong>{tenderCount}</strong></div><div><span>{c.quotation}</span><strong>{quotationCount}</strong></div><div><span>{c.buyers}</span><strong>{buyers.size}</strong></div><div><span>{c.value}</span><strong>{disclosed.length?money(total,'MYR',lang):c.notDisclosed}</strong></div><div><span>{c.market}</span><strong>Sarawak, Malaysia</strong></div></div><div className="panel"><div className="panel-title">{c.history}</div><div className="table-wrap"><div className="table"><div className="row head"><div>{c.date}</div><div>{c.project}</div><div>{c.buyer}</div><div>{c.type}</div><div>{c.amount}</div></div>{history.map(a=><div className="row" key={a.id}><div><b>{a.award_date??'—'}</b></div><div>{a.opportunity_id?<Link className="table-link" href={`/opportunities/${a.opportunity_id}`}>{a.tender_title??a.tender_reference??c.record}</Link>:<strong>{a.tender_title??a.tender_reference??c.record}</strong>}<div className="meta">{a.tender_reference??a.award_reference??'—'}</div>{a.source_url&&<a className="source" href={a.source_url} target="_blank" rel="noreferrer">{c.official} ↗</a>}</div><div>{a.buyer??'—'}</div><div>{a.procurement_type}</div><div>{money(a.awarded_value,a.currency,lang)}</div></div>)}</div></div>{!history.length&&<p className="meta">{c.empty}</p>}</div></div></main>}
