'use client'

import Link from 'next/link'
import {useMemo} from 'react'
import {useI18n} from '@/components/i18n'

type Buyer={canonical_name:string;open_opportunities:number;total_opportunities:number;awards_published:number;unique_winners:number;latest_award_date:string|null;latest_posted_date:string|null;disclosed_award_value:number}
type Op={id:string;title:string;reference:string|null;industry:string|null;posted_date:string|null;closing_date:string|null}
type Award={id:number;tender_title:string|null;tender_reference:string|null;procurement_type:string;awarded_company:string;award_date:string|null;awarded_value:number|null;currency:string;source_url:string|null;award_companies?:{slug:string;canonical_name:string}|null}
type Top={name:string;count:number;slug:string|null}[]

const copy={
 en:{back:'← Opportunities',eyebrow:'BUYER INTELLIGENCE · SARAWAK',lead:'A decision view of this buyer’s observed public procurement activity. Facts come from indexed public records; interpretation is kept separate.',active:'Procurement activity',activeStrong:'Active buyer',activeModerate:'Recently active',activeQuiet:'No recent publishing observed',activeStrongText:'This buyer has open opportunities and recent publishing activity in the indexed data.',activeModerateText:'Recent activity is visible, but current opportunity volume is limited.',activeQuietText:'No recent publishing activity is visible in the records currently indexed.',open:'Open',tracked:'Tracked',awards:'Awards observed',winners:'Winning companies',latestPosted:'Latest published',latestAward:'Latest award',value:'Disclosed award value',focus:'What this buyer is buying',focusNote:'Based on industries assigned to currently indexed opportunities.',current:'Open opportunities',currentNote:'Use this section to see what is actionable now.',posted:'Posted',closing:'Closing',noRef:'No reference',general:'General',frequent:'Observed winning companies',historyNote:'Historical public observation only. It does not imply preference, affiliation or future award likelihood.',observed:'observed awards',recent:'Recent award activity',successful:'Successful tenderer',awardDate:'Award date',amount:'Disclosed value',source:'Official source',public:'Observed public data',trust:'Counts and patterns are based only on public records currently indexed by Borneo Business. They are not a complete procurement history. Verify individual opportunities and awards against the linked official source.',platform:'Platform analysis',platformNote:'Activity labels and category counts are calculated from the indexed records above; they are not official buyer ratings.',none:'No records currently available.'},
 zh:{back:'← 返回商机',eyebrow:'采购方情报 · 砂拉越',lead:'把采购方的公开采购活动整理成可判断的视图。事实来自已收录的公开资料，平台判断会与官方事实分开显示。',active:'采购活跃度',activeStrong:'活跃采购方',activeModerate:'近期有活动',activeQuiet:'近期未观察到发布活动',activeStrongText:'当前有开放商机，同时在已收录资料中可以看到近期发布活动。',activeModerateText:'近期仍有公开活动，但目前开放商机数量有限。',activeQuietText:'在当前已收录的公开资料中，没有观察到近期发布活动。',open:'开放中',tracked:'已收录',awards:'公开中标结果',winners:'中标公司',latestPosted:'最近发布',latestAward:'最近中标',value:'已披露中标金额',focus:'这个采购方主要在采购什么',focusNote:'根据目前已收录商机的产业分类整理。',current:'目前开放商机',currentNote:'先看这里，判断现在有没有值得行动的项目。',posted:'发布日期',closing:'截止日期',noRef:'没有编号',general:'一般',frequent:'公开结果中出现的中标公司',historyNote:'这里只是历史公开资料观察，不代表采购方偏好、关联关系或未来中标可能性。',observed:'笔公开中标',recent:'近期中标活动',successful:'中标公司',awardDate:'中标日期',amount:'已披露金额',source:'官方来源',public:'公开资料观察',trust:'所有统计与模式只基于 Borneo Business 当前已收录的公开记录，并不代表该采购方完整的采购历史。具体商机与中标结果请以官方来源为准。',platform:'平台分析',platformNote:'活跃度与分类统计由平台根据上述已收录公开资料计算，不是采购方官方评级。',none:'目前没有可显示的记录。'},
 ms:{back:'← Kembali ke peluang',eyebrow:'RISIKAN PEMBELI · SARAWAK',lead:'Paparan keputusan berdasarkan aktiviti perolehan awam yang diperhatikan. Fakta datang daripada rekod awam yang diindeks, manakala tafsiran platform dipisahkan dengan jelas.',active:'Aktiviti perolehan',activeStrong:'Pembeli aktif',activeModerate:'Aktif baru-baru ini',activeQuiet:'Tiada penerbitan terkini diperhatikan',activeStrongText:'Pembeli ini mempunyai peluang terbuka dan aktiviti penerbitan terkini dalam data yang diindeks.',activeModerateText:'Aktiviti terkini dapat dilihat tetapi jumlah peluang semasa adalah terhad.',activeQuietText:'Tiada aktiviti penerbitan terkini kelihatan dalam rekod yang kini diindeks.',open:'Terbuka',tracked:'Dijejak',awards:'Anugerah diperhatikan',winners:'Syarikat pemenang',latestPosted:'Terbitan terkini',latestAward:'Anugerah terkini',value:'Nilai anugerah didedahkan',focus:'Apa yang dibeli oleh pembeli ini',focusNote:'Berdasarkan industri yang diberikan kepada peluang yang kini diindeks.',current:'Peluang terbuka',currentNote:'Lihat bahagian ini dahulu untuk memahami apa yang boleh ditindak sekarang.',posted:'Diterbitkan',closing:'Tutup',noRef:'Tiada rujukan',general:'Umum',frequent:'Syarikat pemenang yang diperhatikan',historyNote:'Pemerhatian sejarah awam sahaja. Ia tidak menunjukkan keutamaan, hubungan atau kemungkinan menang pada masa hadapan.',observed:'anugerah diperhatikan',recent:'Aktiviti anugerah terkini',successful:'Pemenang tender',awardDate:'Tarikh anugerah',amount:'Nilai didedahkan',source:'Sumber rasmi',public:'Data awam diperhatikan',trust:'Kiraan dan corak hanya berdasarkan rekod awam yang kini diindeks oleh Borneo Business. Ia bukan sejarah perolehan lengkap. Sahkan setiap peluang dan anugerah dengan sumber rasmi.',platform:'Analisis platform',platformNote:'Label aktiviti dan kiraan kategori dikira daripada rekod yang diindeks di atas; ia bukan penilaian rasmi pembeli.',none:'Tiada rekod untuk dipaparkan buat masa ini.'}
} as const

function daysSince(value:string|null){if(!value)return Number.POSITIVE_INFINITY;const d=new Date(value);if(Number.isNaN(d.getTime()))return Number.POSITIVE_INFINITY;return Math.floor((Date.now()-d.getTime())/86400000)}
function money(value:number){return new Intl.NumberFormat('en-MY',{maximumFractionDigits:0}).format(value)}

export default function BuyerProfileView({buyer,ops,awards,top}:{buyer:Buyer;ops:Op[];awards:Award[];top:Top}){
 const {lang}=useI18n();const c=copy[lang]
 const categories=useMemo(()=>{const m=new Map<string,number>();for(const o of ops){const k=o.industry||c.general;m.set(k,(m.get(k)||0)+1)}return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6)},[ops,c.general])
 const latestAge=daysSince(buyer.latest_posted_date)
 const activity=buyer.open_opportunities>0&&latestAge<=45?{label:c.activeStrong,text:c.activeStrongText,tone:'active'}:latestAge<=90?{label:c.activeModerate,text:c.activeModerateText,tone:'moderate'}:{label:c.activeQuiet,text:c.activeQuietText,tone:'quiet'}
 const openOps=ops.filter(o=>!o.closing_date||o.closing_date>=new Date().toISOString().slice(0,10))
 return <main className="section"><div className="container buyer-intelligence">
   <Link className="source" href="/opportunities">{c.back}</Link>
   <header className="buyer-hero"><div><div className="eyebrow">{c.eyebrow}</div><h1>{buyer.canonical_name}</h1><p className="lead">{c.lead}</p></div><div className={`buyer-activity ${activity.tone}`}><span>{c.active}</span><strong>{activity.label}</strong><p>{activity.text}</p></div></header>

   <section className="buyer-facts" aria-label={c.public}>
    <div><span>{c.open}</span><strong>{buyer.open_opportunities}</strong></div><div><span>{c.tracked}</span><strong>{buyer.total_opportunities}</strong></div><div><span>{c.awards}</span><strong>{buyer.awards_published}</strong></div><div><span>{c.winners}</span><strong>{buyer.unique_winners}</strong></div><div><span>{c.latestPosted}</span><strong>{buyer.latest_posted_date||'—'}</strong></div><div><span>{c.latestAward}</span><strong>{buyer.latest_award_date||'—'}</strong></div>{buyer.disclosed_award_value>0&&<div><span>{c.value}</span><strong>MYR {money(buyer.disclosed_award_value)}</strong></div>}
   </section>

   <div className="buyer-columns">
    <section className="buyer-section"><div className="buyer-section-head"><div><div className="eyebrow">{c.platform}</div><h2>{c.focus}</h2><p>{c.focusNote}</p></div></div>{categories.length?<div className="buyer-category-list">{categories.map(([name,count])=><div key={name}><strong>{name}</strong><span>{count}</span></div>)}</div>:<p className="meta">{c.none}</p>}<div className="buyer-analysis-note">{c.platformNote}</div></section>
    <section className="buyer-section"><div className="buyer-section-head"><div><div className="eyebrow">{c.public}</div><h2>{c.frequent}</h2><p>{c.historyNote}</p></div></div>{top.length?<div className="buyer-company-list">{top.map(item=><div key={item.name}>{item.slug?<Link href={`/companies/${item.slug}`}><strong>{item.name}</strong></Link>:<strong>{item.name}</strong>}<span>{item.count} {c.observed}</span></div>)}</div>:<p className="meta">{c.none}</p>}</section>
   </div>

   <section className="buyer-section buyer-open-section"><div className="buyer-section-head"><div><div className="eyebrow">{c.public}</div><h2>{c.current}</h2><p>{c.currentNote}</p></div><strong className="buyer-count">{openOps.length}</strong></div>{openOps.length?<div className="buyer-op-list">{openOps.slice(0,12).map(o=><article key={o.id}><div><Link href={`/opportunities/${o.id}`}><strong>{o.title}</strong></Link><span>{o.reference||c.noRef} · {o.industry||c.general}</span></div><div><span>{c.posted}</span><strong>{o.posted_date||'—'}</strong></div><div><span>{c.closing}</span><strong>{o.closing_date||'—'}</strong></div><Link className="buyer-row-link" href={`/opportunities/${o.id}`}>→</Link></article>)}</div>:<p className="meta">{c.none}</p>}</section>

   <section className="buyer-section"><div className="buyer-section-head"><div><div className="eyebrow">{c.public}</div><h2>{c.recent}</h2></div></div>{awards.length?<div className="buyer-award-list">{awards.slice(0,20).map(a=><article key={a.id}><div><strong>{a.tender_title||a.tender_reference||c.recent}</strong><span>{a.tender_reference||'—'} · {a.procurement_type}</span></div><div><span>{c.successful}</span>{a.award_companies?.slug?<Link href={`/companies/${a.award_companies.slug}`}><strong>{a.awarded_company}</strong></Link>:<strong>{a.awarded_company}</strong>}</div><div><span>{c.awardDate}</span><strong>{a.award_date||'—'}</strong></div>{a.awarded_value&&a.awarded_value>0?<div><span>{c.amount}</span><strong>{a.currency} {money(a.awarded_value)}</strong></div>:null}{a.source_url?<a className="buyer-source-link" href={a.source_url} target="_blank" rel="noreferrer">{c.source} ↗</a>:null}</article>)}</div>:<p className="meta">{c.none}</p>}</section>

   <div className="source-trust-note"><strong>{c.public}</strong><span>{c.trust}</span></div>
 </div></main>
}
