'use client'

import Link from 'next/link'
import {useI18n} from '@/components/i18n'

type Buyer={canonical_name:string;open_opportunities:number;total_opportunities:number;awards_published:number;unique_winners:number}
type Op={id:string;title:string;reference:string|null;industry:string|null;closing_date:string|null}
type Award={id:number;tender_title:string|null;tender_reference:string|null;procurement_type:string;awarded_company:string;award_date:string|null}
type Top=[string,number][]
const copy={
 en:{back:'← Opportunities',eyebrow:'BUYER PROFILE · SARAWAK',lead:'Observed procurement activity from public records. Use this page to understand what this buyer is publishing and which companies have appeared in published award results.',open:'Open opportunities',tracked:'Opportunities tracked',awards:'Awards observed',winners:'Winning companies',current:'Current opportunities',noRef:'No reference',general:'General',closing:'Closing',frequent:'Companies appearing most often in observed awards',historyNote:'Historical observation only. This does not imply preference, affiliation or future award likelihood.',observed:'observed award',recent:'Recent award activity',result:'Award result',successful:'Successful tenderer',awardDate:'Award date',public:'Observed public data',trust:'Counts are based on records currently indexed by Borneo Business, not the buyer’s complete procurement history. Verify individual records with official sources.'},
 zh:{back:'← 返回商机',eyebrow:'采购方资料 · 砂拉越',lead:'根据公开资料整理采购活动。你可以从这里了解这个采购方近期发布了什么，以及哪些公司曾出现在公开中标结果中。',open:'开放中的商机',tracked:'已收录商机',awards:'已观察中标结果',winners:'中标公司',current:'目前商机',noRef:'没有编号',general:'一般',closing:'截止日期',frequent:'公开中标结果中出现较多的公司',historyNote:'这里只是历史公开资料观察，不代表偏好、关联或未来中标可能性。',observed:'笔公开中标',recent:'近期中标活动',result:'中标结果',successful:'中标公司',awardDate:'中标日期',public:'公开资料观察',trust:'统计只基于 Borneo Business 当前已收录的公开记录，并不代表该采购方完整的采购历史。个别记录请回到官方来源核对。'},
 ms:{back:'← Kembali ke peluang',eyebrow:'PROFIL PEMBELI · SARAWAK',lead:'Aktiviti perolehan yang diperhatikan daripada rekod awam. Gunakan halaman ini untuk melihat apa yang diterbitkan oleh pembeli ini dan syarikat yang muncul dalam keputusan anugerah awam.',open:'Peluang dibuka',tracked:'Peluang dijejak',awards:'Anugerah diperhatikan',winners:'Syarikat pemenang',current:'Peluang semasa',noRef:'Tiada rujukan',general:'Umum',closing:'Tarikh tutup',frequent:'Syarikat yang paling kerap muncul dalam anugerah diperhatikan',historyNote:'Pemerhatian sejarah sahaja. Ini tidak menunjukkan keutamaan, hubungan atau kemungkinan menang pada masa hadapan.',observed:'anugerah diperhatikan',recent:'Aktiviti anugerah terkini',result:'Keputusan anugerah',successful:'Pemenang tender',awardDate:'Tarikh anugerah',public:'Data awam diperhatikan',trust:'Kiraan berdasarkan rekod yang kini diindeks oleh Borneo Business, bukan sejarah perolehan lengkap pembeli. Sahkan rekod individu dengan sumber rasmi.'}
} as const

export default function BuyerProfileView({buyer,ops,awards,top}:{buyer:Buyer;ops:Op[];awards:Award[];top:Top}){const {lang}=useI18n();const c=copy[lang];return <main className="section"><div className="container policy-container"><Link className="source" href="/opportunities">{c.back}</Link><div className="eyebrow">{c.eyebrow}</div><h1>{buyer.canonical_name}</h1><p className="lead">{c.lead}</p><div className="stats-grid"><div><strong>{buyer.open_opportunities}</strong><span>{c.open}</span></div><div><strong>{buyer.total_opportunities}</strong><span>{c.tracked}</span></div><div><strong>{buyer.awards_published}</strong><span>{c.awards}</span></div><div><strong>{buyer.unique_winners}</strong><span>{c.winners}</span></div></div><div className="panel"><div className="panel-title">{c.current}</div>{ops.slice(0,12).map(o=><div className="history-row" key={o.id}><div><Link href={`/opportunities/${o.id}`}><strong>{o.title}</strong></Link><div className="meta">{o.reference||c.noRef} · {o.industry||c.general}</div></div><div><span className="award-label">{c.closing}</span><strong>{o.closing_date||'—'}</strong></div></div>)}</div>{top.length>0&&<div className="panel"><div className="panel-title">{c.frequent}</div><p className="meta">{c.historyNote}</p>{top.map(([name,count])=><div className="history-row" key={name}><strong>{name}</strong><span>{count} {c.observed}</span></div>)}</div>}<div className="panel"><div className="panel-title">{c.recent}</div>{awards.slice(0,20).map(a=><div className="history-row" key={a.id}><div><strong>{a.tender_title||a.tender_reference||c.result}</strong><div className="meta">{a.tender_reference||'—'} · {a.procurement_type}</div></div><div><span className="award-label">{c.successful}</span><strong>{a.awarded_company}</strong></div><div><span className="award-label">{c.awardDate}</span><strong>{a.award_date||'—'}</strong></div></div>)}</div><div className="source-trust-note"><strong>{c.public}</strong><span>{c.trust}</span></div></div></main>}
