'use client'

import { createContext,useContext,useEffect,useState } from 'react'

type Lang='en'|'zh'|'ms'
const dict:Record<Lang,Record<string,string>>={
 en:{opportunities:'Opportunities',market:'Market',signin:'Sign In',join:'Join',guide:'Guide',language:'Language',home:'Home',explore:'Explore Opportunities',enterMarket:'Browse Sarawak Opportunities',latest:'Latest Sarawak opportunities',viewAll:'View all',viewProject:'View project',officialSite:'Official site',officialWebsite:'Official website',sarawakIndexed:'Sarawak opportunities indexed',verifiedDeals:'Verified deals',verifiedBusiness:'Verified business generated',focusedMarket:'Focused market · Sarawak',publicMarket:'Public market',searchIntro:'Search official-source procurement opportunities across Sarawak.',search:'Search opportunity, buyer or reference…',division:'Division',industry:'Industry',status:'Status',open:'Open',closed:'Closed',all:'All',results:'results',buyer:'Buyer',type:'Type',closing:'Closing',details:'Details',projectBrief:'Project brief',likelyNeeds:'What this project likely needs',keyInfo:'Key project information',contactApply:'How to contact / apply',beforeBid:'Before you decide to bid',posted:'Posted',reference:'Reference',procurementType:'Procurement type',takeAction:'Take action',worth:'Worth pursuing?',savePipeline:'Save to Pipeline',buildProfile:'Build company profile',backOpp:'Back to Sarawak Opportunities',next:'Next',back:'Back',start:'Start',radar:'Radar',pipeline:'Pipeline',network:'Network',companyProfile:'Company Profile',signout:'Sign out'},
 zh:{opportunities:'商機',market:'市場',signin:'登入',join:'加入',guide:'使用指南',language:'語言',home:'首頁',explore:'探索商機',enterMarket:'瀏覽砂拉越商機',latest:'最新砂拉越商機',viewAll:'查看全部',viewProject:'查看專案',officialSite:'官方網站',officialWebsite:'官方網站',sarawakIndexed:'已收錄砂拉越商機',verifiedDeals:'已驗證成交',verifiedBusiness:'已驗證業績',focusedMarket:'目前聚焦市場 · 砂拉越',publicMarket:'公開商機市場',searchIntro:'搜尋砂拉越官方來源的公開採購與招標商機。',search:'搜尋標案、採購單位或編號…',division:'地區',industry:'產業',status:'狀態',open:'開放中',closed:'已截止',all:'全部',results:'筆結果',buyer:'採購單位',type:'類型',closing:'截止日期',details:'查看',projectBrief:'專案簡介',likelyNeeds:'這個專案可能需要什麼',keyInfo:'專案重點資料',contactApply:'如何聯絡／投標',beforeBid:'投標前先確認',posted:'公告日期',reference:'標案編號',procurementType:'採購類型',takeAction:'下一步',worth:'值得跟進嗎？',savePipeline:'加入 Pipeline',buildProfile:'建立公司資料',backOpp:'返回砂拉越商機',next:'下一步',back:'上一步',start:'開始使用',radar:'商機雷達',pipeline:'Pipeline',network:'合作網絡',companyProfile:'公司資料',signout:'登出'},
 ms:{opportunities:'Peluang',market:'Pasaran',signin:'Log Masuk',join:'Daftar',guide:'Panduan',language:'Bahasa',home:'Utama',explore:'Terokai Peluang',enterMarket:'Lihat Peluang Sarawak',latest:'Peluang terkini di Sarawak',viewAll:'Lihat semua',viewProject:'Lihat projek',officialSite:'Laman rasmi',officialWebsite:'Laman rasmi',sarawakIndexed:'Peluang Sarawak diindeks',verifiedDeals:'Urus niaga disahkan',verifiedBusiness:'Nilai perniagaan disahkan',focusedMarket:'Pasaran fokus · Sarawak',publicMarket:'Pasaran peluang awam',searchIntro:'Cari peluang perolehan daripada sumber rasmi di seluruh Sarawak.',search:'Cari peluang, pembeli atau rujukan…',division:'Bahagian',industry:'Industri',status:'Status',open:'Dibuka',closed:'Ditutup',all:'Semua',results:'hasil',buyer:'Pembeli / Agensi',type:'Jenis',closing:'Tarikh tutup',details:'Butiran',projectBrief:'Ringkasan projek',likelyNeeds:'Keperluan projek yang mungkin',keyInfo:'Maklumat utama projek',contactApply:'Cara hubungi / memohon',beforeBid:'Sebelum membuat bidaan',posted:'Tarikh iklan',reference:'Rujukan',procurementType:'Jenis perolehan',takeAction:'Tindakan',worth:'Berbaloi diteruskan?',savePipeline:'Simpan ke Pipeline',buildProfile:'Bina profil syarikat',backOpp:'Kembali ke Peluang Sarawak',next:'Seterusnya',back:'Kembali',start:'Mula',radar:'Radar',pipeline:'Pipeline',network:'Rangkaian',companyProfile:'Profil Syarikat',signout:'Log Keluar'}
}

const C=createContext<{lang:Lang;setLang:(l:Lang)=>void;t:(k:string)=>string}>({lang:'en',setLang:()=>{},t:k=>k})
export function LanguageProvider({children}:{children:React.ReactNode}){
 const [lang,setLangState]=useState<Lang>('en')
 useEffect(()=>{const saved=localStorage.getItem('borneo-lang') as Lang|null;if(saved&&['en','zh','ms'].includes(saved))setLangState(saved)},[])
 function setLang(l:Lang){setLangState(l);localStorage.setItem('borneo-lang',l);document.documentElement.lang=l==='zh'?'zh-Hant':l}
 return <C.Provider value={{lang,setLang,t:(k)=>dict[lang][k]??k}}>{children}</C.Provider>
}
export function useI18n(){return useContext(C)}
export function T({k}:{k:string}){const {t}=useI18n();return <>{t(k)}</>}
