'use client'

import { createContext,useContext,useEffect,useState } from 'react'

type Lang='en'|'zh'|'ms'
const dict:Record<Lang,Record<string,string>>={
 en:{opportunities:'Opportunities',market:'Market',signin:'Sign In',join:'Join',guide:'Guide',language:'Language',home:'Home',explore:'Explore Opportunities',enterMarket:'Browse Sarawak Opportunities',headline:'See where business is happening across Sarawak.',lead:'Discover official public opportunities, understand each project in plain language, identify active buyers and build the right business connections across Sarawak.',latest:'Latest Sarawak opportunities',viewAll:'View all',viewProject:'View project',officialSite:'Official site',officialWebsite:'Official website',sarawakIndexed:'Sarawak opportunities indexed',verifiedDeals:'Verified deals',verifiedBusiness:'Verified business generated',focusedMarket:'Focused market · Sarawak',publicMarket:'Public market',searchIntro:'Search official-source procurement opportunities across Sarawak.',search:'Search opportunity, buyer or reference…',division:'Division',industry:'Industry',status:'Status',open:'Open',closed:'Closed',all:'All',results:'results',page:'Page',previousPage:'Previous page',nextPage:'Next page',buyer:'Buyer',type:'Type',closing:'Closing',details:'Details',projectBrief:'Project brief',likelyNeeds:'What this project likely needs',keyInfo:'Key project information',contactApply:'How to contact / apply',beforeBid:'Before you decide to bid',posted:'Posted',reference:'Reference',procurementType:'Procurement type',takeAction:'Take action',worth:'Worth pursuing?',savePipeline:'Save to Pipeline',buildProfile:'Build company profile',backOpp:'Back to Sarawak Opportunities',next:'Next',back:'Back',start:'Start',radar:'Radar',pipeline:'Pipeline',network:'Network',companyProfile:'Company Profile',signout:'Sign out',officialSourceIntel:'Official-source project intelligence',footer:'Sarawak public-source intelligence with source attribution. Always verify requirements on the official procurement website.'},
 zh:{opportunities:'商机',market:'市场',signin:'登录',join:'加入',guide:'使用指南',language:'语言',home:'首页',explore:'探索商机',enterMarket:'浏览砂拉越商机',headline:'看见砂拉越正在发生的生意。',lead:'集中查看官方公开商机，用简单方式先看懂项目、采购单位与需求，再决定要不要深入跟进。',latest:'最新砂拉越商机',viewAll:'查看全部',viewProject:'查看项目',officialSite:'官方网站',officialWebsite:'官方网站',sarawakIndexed:'已收录砂拉越商机',verifiedDeals:'已验证成交',verifiedBusiness:'已验证业绩',focusedMarket:'目前聚焦市场 · 砂拉越',publicMarket:'公开商机市场',searchIntro:'搜索砂拉越官方来源的公开采购与招标商机。',search:'搜索标案、采购单位或编号…',division:'地区',industry:'行业',status:'状态',open:'开放中',closed:'已截止',all:'全部',results:'条结果',page:'第',previousPage:'上一页',nextPage:'下一页',buyer:'采购单位',type:'类型',closing:'截止日期',details:'查看',projectBrief:'项目简介',likelyNeeds:'这个项目可能需要什么',keyInfo:'项目重点资料',contactApply:'如何联系／投标',beforeBid:'投标前先确认',posted:'公告日期',reference:'标案编号',procurementType:'采购类型',takeAction:'下一步',worth:'值得跟进吗？',savePipeline:'加入 Pipeline',buildProfile:'建立公司资料',backOpp:'返回砂拉越商机',next:'下一步',back:'上一步',start:'开始使用',radar:'商机雷达',pipeline:'Pipeline',network:'合作网络',companyProfile:'公司资料',signout:'登出',officialSourceIntel:'官方来源项目情报',footer:'本平台整理砂拉越公开来源信息并保留来源链接；正式投标前请以官方采购网站资料为准。'},
 ms:{opportunities:'Peluang',market:'Pasaran',signin:'Log Masuk',join:'Daftar',guide:'Panduan',language:'Bahasa',home:'Utama',explore:'Terokai Peluang',enterMarket:'Lihat Peluang Sarawak',headline:'Lihat di mana perniagaan sedang berlaku di Sarawak.',lead:'Temui peluang awam rasmi, fahami projek dalam bahasa mudah, kenal pasti agensi aktif dan bina hubungan perniagaan yang sesuai di Sarawak.',latest:'Peluang terkini di Sarawak',viewAll:'Lihat semua',viewProject:'Lihat projek',officialSite:'Laman rasmi',officialWebsite:'Laman rasmi',sarawakIndexed:'Peluang Sarawak diindeks',verifiedDeals:'Urus niaga disahkan',verifiedBusiness:'Nilai perniagaan disahkan',focusedMarket:'Pasaran fokus · Sarawak',publicMarket:'Pasaran peluang awam',searchIntro:'Cari peluang perolehan daripada sumber rasmi di seluruh Sarawak.',search:'Cari peluang, pembeli atau rujukan…',division:'Bahagian',industry:'Industri',status:'Status',open:'Dibuka',closed:'Ditutup',all:'Semua',results:'hasil',page:'Halaman',previousPage:'Halaman sebelumnya',nextPage:'Halaman seterusnya',buyer:'Pembeli / Agensi',type:'Jenis',closing:'Tarikh tutup',details:'Butiran',projectBrief:'Ringkasan projek',likelyNeeds:'Keperluan projek yang mungkin',keyInfo:'Maklumat utama projek',contactApply:'Cara hubungi / memohon',beforeBid:'Sebelum membuat bidaan',posted:'Tarikh iklan',reference:'Rujukan',procurementType:'Jenis perolehan',takeAction:'Tindakan',worth:'Berbaloi diteruskan?',savePipeline:'Simpan ke Pipeline',buildProfile:'Bina profil syarikat',backOpp:'Kembali ke Peluang Sarawak',next:'Seterusnya',back:'Kembali',start:'Mula',radar:'Radar',pipeline:'Pipeline',network:'Rangkaian',companyProfile:'Profil Syarikat',signout:'Log Keluar',officialSourceIntel:'Maklumat projek daripada sumber rasmi',footer:'Maklumat sumber awam Sarawak dengan pautan asal. Sila sahkan semua syarat di laman perolehan rasmi sebelum membida.'}
}

const C=createContext<{lang:Lang;setLang:(l:Lang)=>void;t:(k:string)=>string}>({lang:'en',setLang:()=>{},t:k=>k})
export function LanguageProvider({children}:{children:React.ReactNode}){
 const [lang,setLangState]=useState<Lang>('en')
 useEffect(()=>{const saved=localStorage.getItem('borneo-lang') as Lang|null;if(saved&&['en','zh','ms'].includes(saved)){setLangState(saved);document.documentElement.lang=saved==='zh'?'zh-Hans':saved}},[])
 function setLang(l:Lang){setLangState(l);localStorage.setItem('borneo-lang',l);document.documentElement.lang=l==='zh'?'zh-Hans':l}
 return <C.Provider value={{lang,setLang,t:(k)=>dict[lang][k]??k}}>{children}</C.Provider>
}
export function useI18n(){return useContext(C)}
export function T({k}:{k:string}){const {t}=useI18n();return <>{t(k)}</>}
