'use client'

import {useState} from 'react'
import {useI18n} from '@/components/i18n'

const copy={
 en:{preparing:'Preparing PDF…',download:'Download official source PDF',note:'Uses the linked public notice. If the agency publishes a PDF, the original file is downloaded; otherwise a source copy is generated without rewriting the tender content.',retrieve:'Unable to retrieve official source',prepare:'Unable to prepare PDF',copy:'OFFICIAL SOURCE COPY',ref:'Reference',source:'Source',notPublished:'Not published',footer:'Generated by Borneo Business from the linked public source for reading convenience. The procuring agency source remains authoritative.'},
 zh:{preparing:'正在准备 PDF…',download:'下载官方来源 PDF',note:'使用当前链接的公开公告。若采购方发布原始 PDF，会直接下载原文件；否则只生成官方来源副本，不改写标案内容。',retrieve:'无法取得官方来源',prepare:'无法准备 PDF',copy:'官方来源副本',ref:'标案编号',source:'来源',notPublished:'未公开',footer:'由 Borneo Business 根据链接的公开来源生成，仅方便阅读。采购方官方来源仍具有最终权威性。'},
 ms:{preparing:'Menyediakan PDF…',download:'Muat turun PDF sumber rasmi',note:'Menggunakan notis awam yang dipautkan. Jika agensi menerbitkan PDF, fail asal dimuat turun; jika tidak, salinan sumber dijana tanpa menulis semula kandungan tender.',retrieve:'Tidak dapat mendapatkan sumber rasmi',prepare:'Tidak dapat menyediakan PDF',copy:'SALINAN SUMBER RASMI',ref:'Rujukan',source:'Sumber',notPublished:'Tidak diterbitkan',footer:'Dijana oleh Borneo Business daripada sumber awam yang dipautkan untuk kemudahan membaca. Sumber agensi perolehan kekal berkuasa.'}
} as const

export default function OfficialPdfButton({sourceUrl,reference}:{sourceUrl:string;reference:string|null}){
 const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const {lang}=useI18n();const c=copy[lang]
 async function download(){setBusy(true);setMessage('');try{
  const res=await fetch(`/api/official-source-copy?url=${encodeURIComponent(sourceUrl)}`)
  if(!res.ok){const d=await res.json().catch(()=>({error:c.retrieve}));throw new Error(d.error||c.retrieve)}
  const type=res.headers.get('content-type')||''
  if(type.includes('application/pdf')){const blob=await res.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${reference||'official-tender'}-official.pdf`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);return}
  const data=await res.json();const {jsPDF}=await import('jspdf');const doc=new jsPDF({unit:'mm',format:'a4'});const margin=15,pageWidth=210,pageHeight=297,maxWidth=180
  doc.setFont('helvetica','bold');doc.setFontSize(15);doc.text(c.copy,margin,18);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text(`${c.ref}: ${reference||c.notPublished}`,margin,25);doc.text(`${c.source}:`,margin,30);const sourceLines=doc.splitTextToSize(sourceUrl,maxWidth-13);doc.text(sourceLines,28,30);let y=38+Math.max(0,sourceLines.length-1)*4;doc.setDrawColor(210);doc.line(margin,y,195,y);y+=7;doc.setFontSize(9.5);const lines=doc.splitTextToSize(data.text,maxWidth);for(const line of lines){if(y>pageHeight-18){doc.addPage();y=18}doc.text(line,margin,y);y+=4.3}if(y>pageHeight-24){doc.addPage();y=18}else y+=5;doc.setFontSize(8);doc.text(c.footer,margin,y,{maxWidth});const safe=(reference||'official-tender').replace(/[^a-z0-9-_]+/gi,'-');doc.save(`${safe}-official-source-copy.pdf`)
 }catch(e){setMessage(e instanceof Error?e.message:c.prepare)}finally{setBusy(false)}}
 return <div className="official-pdf-action"><button className="btn" onClick={download} disabled={busy}>{busy?c.preparing:c.download}</button><small>{c.note}</small>{message&&<span className="translation-error">{message}</span>}</div>
}
