'use client'

import {useState} from 'react'

export default function OfficialPdfButton({sourceUrl,reference}:{sourceUrl:string;reference:string|null}){
  const [busy,setBusy]=useState(false)
  const [message,setMessage]=useState('')

  async function download(){
    setBusy(true);setMessage('')
    try{
      const res=await fetch(`/api/official-source-copy?url=${encodeURIComponent(sourceUrl)}`)
      if(!res.ok){const d=await res.json().catch(()=>({error:'Unable to retrieve official source'}));throw new Error(d.error||'Unable to retrieve official source')}
      const type=res.headers.get('content-type')||''
      if(type.includes('application/pdf')){
        const blob=await res.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${reference||'official-tender'}-official.pdf`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);return
      }
      const data=await res.json()
      const {jsPDF}=await import('jspdf')
      const doc=new jsPDF({unit:'mm',format:'a4'})
      const margin=15,pageWidth=210,pageHeight=297,maxWidth=180
      doc.setFont('helvetica','bold');doc.setFontSize(15);doc.text('OFFICIAL SOURCE COPY',margin,18)
      doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text(`Reference: ${reference||'Not published'}`,margin,25)
      doc.text('Source:',margin,30);const sourceLines=doc.splitTextToSize(sourceUrl,maxWidth-13);doc.text(sourceLines,28,30)
      let y=38+Math.max(0,sourceLines.length-1)*4
      doc.setDrawColor(210);doc.line(margin,y,195,y);y+=7
      doc.setFontSize(9.5)
      const lines=doc.splitTextToSize(data.text,maxWidth)
      for(const line of lines){if(y>pageHeight-18){doc.addPage();y=18}doc.text(line,margin,y);y+=4.3}
      if(y>pageHeight-24){doc.addPage();y=18}else y+=5
      doc.setFontSize(8);doc.text('Generated by Borneo Business from the linked public source for reading convenience. The procuring agency source remains authoritative.',margin,y,{maxWidth})
      const safe=(reference||'official-tender').replace(/[^a-z0-9-_]+/gi,'-')
      doc.save(`${safe}-official-source-copy.pdf`)
    }catch(e){setMessage(e instanceof Error?e.message:'Unable to prepare PDF')}
    finally{setBusy(false)}
  }

  return <div className="official-pdf-action"><button className="btn" onClick={download} disabled={busy}>{busy?'Preparing PDF…':'Download official source PDF'}</button><small>Uses the linked public notice. If the agency publishes a PDF, the original file is downloaded; otherwise a source copy is generated without rewriting the tender content.</small>{message&&<span className="translation-error">{message}</span>}</div>
}
