'use client'

import Link from 'next/link'
import {useI18n} from '@/components/i18n'
import ContextInfoDrawer from '@/components/context-info-drawer'
import OfficialPdfButton from '@/components/official-pdf-button'
import OpportunityPipelineAction from '@/components/opportunity-pipeline-action'
import type {Opportunity,OpportunityAward} from '@/lib/data'
import type {ProcurementTerm} from '@/lib/procurement-terms'
import type {OfficialTenderSnapshot} from '@/lib/official-tender-source'

type BuyerInfo={display:string;fullName:string}

const copy={
 en:{back:'← Back to opportunities',eyebrow:'PUBLIC PROCUREMENT · SARAWAK',open:'Open',closed:'Closed',awarded:'Awarded',officialData:'Official Data',projectInfo:'Tender information',officialFacts:'Official information currently retrievable from the public source.',buyer:'Buyer / agency',reference:'Reference',market:'Market',posted:'Posted',closing:'Closing',type:'Type',notPublished:'Not published',officialDocument:'Official document',officialRecord:'Official public record',noExtraFacts:'No additional structured fields were retrievable. Use the official source for the complete notice.',keyDates:'Key dates',published:'Published',deadline:'Submission deadline',awardPublished:'Award published',eligibility:'Eligibility',eligibilityNote:'Only requirements explicitly visible in the indexed official source are shown.',notStated:'Not stated in the indexed official source',content:'Tender content',contentNote:'Original wording from the official source. Not translated or rewritten.',contentFallback:'No separate description or scope field was retrievable. Refer to the official document for the complete original notice.',lockedEyebrow:'SUBSCRIBED INTELLIGENCE',lockedTitle:'Advanced tender intelligence',lockedText:'These tools are designed to reduce the time needed to understand, qualify and act on a tender.',subscribe:'View subscription',save:'Save opportunity',trust:'Source & trust',trustText:'Official facts remain traceable to the original source. Borneo Business is an independent platform and does not replace the issuing agency or official procurement process.',officialSource:'Open official source ↗',lastChecked:'Last checked',features:['30-Second Brief','Real Checklist','Red Flags','Decision Intelligence','Buyer History','Similar Awards','Company Gap Analysis','Tender Change Tracking']},
 zh:{back:'← 返回商机',eyebrow:'公开采购 · 砂拉越',open:'开放中',closed:'已截止',awarded:'已公布中标',officialData:'官方资料',projectInfo:'完整标案信息',officialFacts:'以下为平台目前可从官方公开来源取得的官方信息。',buyer:'采购方／发标单位',reference:'标案编号',market:'地区',posted:'发布日期',closing:'截止日期',type:'采购类型',notPublished:'未公开',officialDocument:'官方文件',officialRecord:'官方公开记录',noExtraFacts:'目前无法取得更多结构化字段，请以官方来源中的完整公告为准。',keyDates:'关键时间',published:'发布',deadline:'投标截止',awardPublished:'中标结果公布',eligibility:'资格条件',eligibilityNote:'这里只显示已收录官方来源中明确写出的条件。',notStated:'已收录官方来源未明确说明',content:'标案内容',contentNote:'保留官方来源原文，不翻译、不改写。',contentFallback:'目前无法从官方页面独立取得 Description / Scope 字段，请直接查看官方文件中的完整原文。',lockedEyebrow:'订阅情报',lockedTitle:'进阶标案情报',lockedText:'这些功能的目标不是增加更多内容，而是减少看懂标案、确认资格与决定是否投入所需的时间。',subscribe:'查看订阅方案',save:'保存商机',trust:'来源与可信度',trustText:'官方事实会保留原始来源追溯。Borneo Business 是独立平台，不取代采购方或正式投标流程。',officialSource:'打开官方来源 ↗',lastChecked:'最后检查',features:['30 秒标案摘要','真实准备清单','风险提醒','决策辅助','采购方历史','类似中标记录','公司条件缺口分析','标案变更追踪']},
 ms:{back:'← Kembali ke peluang',eyebrow:'PEROLEHAN AWAM · SARAWAK',open:'Terbuka',closed:'Ditutup',awarded:'Anugerah diterbitkan',officialData:'Data Rasmi',projectInfo:'Maklumat tender lengkap',officialFacts:'Maklumat rasmi yang kini boleh diambil daripada sumber awam.',buyer:'Pembeli / agensi',reference:'Rujukan',market:'Pasaran',posted:'Diterbitkan',closing:'Tarikh tutup',type:'Jenis',notPublished:'Tidak diterbitkan',officialDocument:'Dokumen rasmi',officialRecord:'Rekod awam rasmi',noExtraFacts:'Tiada medan berstruktur tambahan dapat diperoleh. Rujuk sumber rasmi untuk notis penuh.',keyDates:'Tarikh penting',published:'Diterbitkan',deadline:'Tarikh akhir penghantaran',awardPublished:'Anugerah diterbitkan',eligibility:'Kelayakan',eligibilityNote:'Hanya syarat yang dinyatakan dengan jelas dalam sumber rasmi diindeks dipaparkan.',notStated:'Tidak dinyatakan dalam sumber rasmi diindeks',content:'Kandungan tender',contentNote:'Kandungan asal daripada sumber rasmi. Tidak diterjemah atau ditulis semula.',contentFallback:'Medan description / scope berasingan tidak dapat diperoleh. Rujuk dokumen rasmi untuk kandungan asal penuh.',lockedEyebrow:'RISIKAN LANGGANAN',lockedTitle:'Risikan tender lanjutan',lockedText:'Fungsi ini direka untuk mengurangkan masa memahami tender, menyemak kelayakan dan membuat keputusan.',subscribe:'Lihat langganan',save:'Simpan peluang',trust:'Sumber & kepercayaan',trustText:'Fakta rasmi kekal boleh dijejaki kepada sumber asal. Borneo Business ialah platform bebas dan tidak menggantikan agensi penerbit atau proses perolehan rasmi.',officialSource:'Buka sumber rasmi ↗',lastChecked:'Semakan terakhir',features:['Ringkasan 30 Saat','Senarai Semak Sebenar','Amaran Risiko','Sokongan Keputusan','Sejarah Pembeli','Anugerah Serupa','Analisis Jurang Syarikat','Penjejakan Perubahan Tender']}
} as const

function findOfficial(snapshot:OfficialTenderSnapshot,pattern:RegExp){return snapshot.fields.filter(f=>pattern.test(f.label)).map(f=>`${f.label}: ${f.value}`)}

export default function OpportunityFreeDetailView({opportunity,awards,buyerInfo,pageTerms,snapshot}:{opportunity:Opportunity;awards:OpportunityAward[];buyerInfo:BuyerInfo;pageTerms:ProcurementTerm[];snapshot:OfficialTenderSnapshot}){
 const {lang}=useI18n();const c=copy[lang]
 const today=new Date().toISOString().slice(0,10);const isOpen=!opportunity.closing_date||opportunity.closing_date>=today;const hasAward=awards.length>0
 const eligibility=findOfficial(snapshot,/CIDB|UPKJ|MOF|grade|class|category|head|sub.?head|bumiputera|registration|kelayakan|pendaftaran/i)
 return <main className="section"><div className="container tender-detail-v2">
  <Link className="source back-link" href="/opportunities">{c.back}</Link>
  <header className="tender-title-block"><div className="eyebrow">{c.eyebrow}</div><h1>{opportunity.title}</h1><div className="tender-head-meta"><span className={`status-pill ${hasAward?'awarded':isOpen?'open':'closed'}`}>{hasAward?c.awarded:isOpen?c.open:c.closed}</span><span>{opportunity.reference??c.notPublished}</span><span>{buyerInfo.display}</span><span>{opportunity.closing_date??'—'}</span></div></header>

  <section className="tender-section"><div className="tender-section-head"><div><div className="eyebrow">{c.officialData}</div><h2>{c.projectInfo}</h2><p>{c.officialFacts}</p></div><ContextInfoDrawer terms={pageTerms}/></div>
   <div className="tender-core-facts"><div><span>{c.buyer}</span><strong>{buyerInfo.display}</strong>{buyerInfo.fullName!==buyerInfo.display&&<small>{buyerInfo.fullName}</small>}</div><div><span>{c.reference}</span><strong>{opportunity.reference??'—'}</strong></div><div><span>{c.market}</span><strong>Sarawak, Malaysia</strong></div><div><span>{c.posted}</span><strong>{opportunity.posted_date??'—'}</strong></div><div><span>{c.closing}</span><strong>{opportunity.closing_date??'—'}</strong></div><div><span>{c.type}</span><strong>{opportunity.opportunity_type}</strong></div></div>
   {snapshot.fields.length?<div className="official-fact-table">{snapshot.fields.map((f,i)=><div key={`${f.label}-${i}`}><span>{f.label}</span><strong>{f.value}</strong></div>)}</div>:<p className="meta">{c.noExtraFacts}</p>}
   <div className="official-document-row"><div><strong>{c.officialDocument}</strong><span>{snapshot.sourceName||c.officialRecord}</span></div><OfficialPdfButton sourceUrl={opportunity.source_url} reference={opportunity.reference}/></div>
  </section>

  <section className="tender-section"><div className="tender-section-head"><div><div className="eyebrow">{c.officialData}</div><h2>{c.keyDates}</h2></div></div><div className="key-date-line"><div><span>01</span><strong>{c.published}</strong><b>{opportunity.posted_date??'—'}</b></div><div><span>02</span><strong>{c.deadline}</strong><b>{opportunity.closing_date??'—'}</b></div>{awards.slice(0,1).map(a=><div key={a.id}><span>03</span><strong>{c.awardPublished}</strong><b>{a.award_date??'—'}</b></div>)}</div></section>

  <section className="tender-section"><div className="tender-section-head"><div><div className="eyebrow">{c.officialData}</div><h2>{c.eligibility}</h2><p>{c.eligibilityNote}</p></div></div>{eligibility.length?<ul className="plain-check-list official">{eligibility.map(x=><li key={x}>{x}</li>)}</ul>:<p className="empty-official">{c.notStated}</p>}</section>

  <details className="tender-fold" open><summary><div><span className="eyebrow">{c.officialData}</span><strong>{c.content}</strong><small>{c.contentNote}</small></div><span>＋</span></summary><div className="tender-fold-body">{snapshot.content.length?snapshot.content.map((x,i)=><p className="official-original-copy" key={i}>{x}</p>):<p className="meta">{c.contentFallback}</p>}</div></details>

  <section className="tender-login-gate"><div><div className="eyebrow">{c.lockedEyebrow}</div><h2>{c.lockedTitle}</h2><p>{c.lockedText}</p><div className="subscription-feature-list">{c.features.map(feature=><span key={feature}>{feature}</span>)}</div></div><div className="tender-login-actions"><Link className="btn primary" href="/subscribe">{c.subscribe}</Link></div></section>

  {!hasAward&&<div className="tender-bottom-action"><span className="eyebrow">{c.save}</span><OpportunityPipelineAction opportunityId={opportunity.id}/></div>}

  <section className="tender-trust"><div><div className="eyebrow">{c.trust}</div><p>{c.trustText}</p><div className="trust-meta"><span>{c.lastChecked}: {opportunity.last_checked_at??'—'}</span><span>{c.reference}: {opportunity.reference??c.notPublished}</span></div></div><div className="trust-actions"><a className="source" href={opportunity.source_url} target="_blank" rel="noreferrer">{c.officialSource}</a></div></section>
 </div></main>
}
