'use client'

import Link from 'next/link'
import {useI18n} from '@/components/i18n'
import ContextInfoDrawer from '@/components/context-info-drawer'
import OfficialPdfButton from '@/components/official-pdf-button'
import OpportunityPipelineAction from '@/components/opportunity-pipeline-action'
import ReportDataIssue from '@/components/report-data-issue'
import type {Opportunity,OpportunityAward} from '@/lib/data'
import type {BidAssessment} from '@/lib/matching'
import type {ProcurementTerm} from '@/lib/procurement-terms'
import type {OfficialTenderSnapshot} from '@/lib/official-tender-source'

type BuyerInfo={display:string;fullName:string}
type BuyerLink={slug:string;canonical_name:string}|null

const copy={
 en:{back:'← Back to opportunities',eyebrow:'PUBLIC PROCUREMENT · SARAWAK',open:'Open',closed:'Closed',awarded:'Awarded',general:'General',source:'Source',official:'Official public record',lastChecked:'Last checked',reference:'Reference',notPublished:'Not published',information:'Information',projectInfo:'Tender information',officialData:'Official Data',buyer:'Buyer / agency',market:'Market',posted:'Posted',closing:'Closing',type:'Type',officialDocument:'Official document',officialFacts:'Complete official facts currently retrievable from the public source.',noExtraFacts:'No additional structured fields were retrievable. Use the official source for the full notice.',keyDates:'Key dates',published:'Published',deadline:'Submission deadline',awardPublished:'Award published',eligibility:'Eligibility',eligibilityNote:'Only requirements explicitly visible in the indexed official source are shown here. Nothing is inferred as an official requirement.',notStated:'Not stated in the indexed official source',content:'Tender content',contentNote:'Original wording from the official source. Not translated or rewritten.',contentFallback:'No separate description or scope field was retrievable from the official page. Refer to the official document for the complete original notice.',summary:'Tender summary',summaryLabel:'Platform Summary',summaryText:'This is a public procurement opportunity issued by {buyer}. Review the official scope, eligibility, dates and submission instructions before committing bid resources.',prepare:'What to prepare',prepareLabel:'Platform Checklist',prepareNote:'A practical checklist derived from the indexed official information. Items marked as confirmation points must be verified against the official notice.',howSubmit:'How to participate',submitNote:'Follow only the official submission method and address stated by the procuring agency.',buyerContext:'Buyer context',buyerContextText:'View this procurement in the context of the issuing organization and its observed public activity.',viewBuyer:'View Buyer Intelligence →',timeline:'Tender timeline',trust:'Source & trust',trustText:'Official facts are kept separate from platform summaries and checklists. Borneo Business is independent and does not replace the issuing agency or official procurement process.',officialSource:'Open official source ↗',report:'Report incorrect or outdated data',assessment:'Decision support',worth:'Worth considering',review:'Review first',low:'Not recommended',profile:'Add company details',addProfile:'Add company details for a more relevant assessment.',next:'Next step',confirmEligibility:'Confirm eligibility and registration',reviewDocs:'Review the official document and scope',checkBriefing:'Check site visit / briefing requirements',prepareSubmission:'Prepare all required submission documents',confirmDeadline:'Confirm closing date, time and delivery method'},
 zh:{back:'← 返回商机',eyebrow:'公开采购 · 砂拉越',open:'开放中',closed:'已截止',awarded:'已公布中标',general:'一般',source:'来源',official:'官方公开记录',lastChecked:'最后检查',reference:'标案编号',notPublished:'未公开',information:'标案信息',projectInfo:'完整标案信息',officialData:'官方资料',buyer:'采购方／发标单位',market:'地区',posted:'发布日期',closing:'截止日期',type:'采购类型',officialDocument:'官方文件',officialFacts:'以下为平台目前可从官方公开来源取得的完整结构化资料。',noExtraFacts:'目前无法取得更多结构化字段，请以官方来源中的完整公告为准。',keyDates:'关键时间',published:'发布',deadline:'投标截止',awardPublished:'中标结果公布',eligibility:'资格条件',eligibilityNote:'这里只显示已收录官方来源中明确写出的条件，不会把平台推测当作官方资格要求。',notStated:'已收录官方来源未明确说明',content:'标案内容',contentNote:'保留官方来源原文，不翻译、不改写。',contentFallback:'目前无法从官方页面独立取得 Description / Scope 字段，请直接查看官方文件中的完整原文。',summary:'标案简介',summaryLabel:'平台简介',summaryText:'这是由 {buyer} 发布的公开采购项目。决定投入投标资源前，应先核对官方工作范围、资格条件、关键日期与提交方式。',prepare:'标案需准备什么',prepareLabel:'平台整理清单',prepareNote:'根据已收录官方信息整理的实用清单；凡涉及资格、文件与提交要求，仍需回到官方公告确认。',howSubmit:'如何投标',submitNote:'提交方式、地点和文件要求只以采购方官方公告为准。',buyerContext:'采购方背景',buyerContextText:'把这笔标案放回发标单位的公开采购活动中理解。',viewBuyer:'查看采购方情报 →',timeline:'标案时间线',trust:'来源与可信度',trustText:'官方事实、平台简介与平台整理清单会明确分开。Borneo Business 是独立平台，不取代采购方或正式投标流程。',officialSource:'打开官方来源 ↗',report:'回报错误或过时资料',assessment:'决策辅助',worth:'值得考虑',review:'先检查条件',low:'不建议优先投入',profile:'补充公司资料',addProfile:'补充公司资料后，可以得到更相关的判断。',next:'下一步',confirmEligibility:'确认资格与注册要求',reviewDocs:'阅读官方文件与工作范围',checkBriefing:'确认 Site Visit／Briefing 要求',prepareSubmission:'准备所有要求提交的文件',confirmDeadline:'确认截止日期、时间与提交方式'},
 ms:{back:'← Kembali ke peluang',eyebrow:'PEROLEHAN AWAM · SARAWAK',open:'Terbuka',closed:'Ditutup',awarded:'Anugerah diterbitkan',general:'Umum',source:'Sumber',official:'Rekod awam rasmi',lastChecked:'Semakan terakhir',reference:'Rujukan',notPublished:'Tidak diterbitkan',information:'Maklumat',projectInfo:'Maklumat tender lengkap',officialData:'Data Rasmi',buyer:'Pembeli / agensi',market:'Pasaran',posted:'Diterbitkan',closing:'Tarikh tutup',type:'Jenis',officialDocument:'Dokumen rasmi',officialFacts:'Maklumat berstruktur lengkap yang kini boleh diambil daripada sumber awam rasmi.',noExtraFacts:'Tiada medan berstruktur tambahan dapat diperoleh. Rujuk sumber rasmi untuk notis penuh.',keyDates:'Tarikh penting',published:'Diterbitkan',deadline:'Tarikh akhir penghantaran',awardPublished:'Anugerah diterbitkan',eligibility:'Kelayakan',eligibilityNote:'Hanya syarat yang dinyatakan dengan jelas dalam sumber rasmi diindeks dipaparkan. Tiada syarat rasmi dibuat berdasarkan andaian platform.',notStated:'Tidak dinyatakan dalam sumber rasmi diindeks',content:'Kandungan tender',contentNote:'Kandungan asal daripada sumber rasmi. Tidak diterjemah atau ditulis semula.',contentFallback:'Medan description / scope berasingan tidak dapat diperoleh. Rujuk dokumen rasmi untuk kandungan asal penuh.',summary:'Ringkasan tender',summaryLabel:'Ringkasan Platform',summaryText:'Ini ialah peluang perolehan awam yang diterbitkan oleh {buyer}. Semak skop rasmi, kelayakan, tarikh penting dan kaedah penghantaran sebelum menggunakan sumber untuk membida.',prepare:'Apa yang perlu disediakan',prepareLabel:'Senarai Semak Platform',prepareNote:'Senarai praktikal berdasarkan maklumat rasmi yang diindeks. Keperluan kelayakan, dokumen dan penghantaran mesti disahkan pada notis rasmi.',howSubmit:'Cara menyertai',submitNote:'Ikut hanya kaedah, alamat dan keperluan penghantaran yang dinyatakan oleh agensi perolehan.',buyerContext:'Konteks pembeli',buyerContextText:'Fahami tender ini dalam konteks aktiviti perolehan awam organisasi penerbit.',viewBuyer:'Lihat Risikan Pembeli →',timeline:'Garis masa tender',trust:'Sumber & kepercayaan',trustText:'Fakta rasmi dipisahkan daripada ringkasan dan senarai semak platform. Borneo Business ialah platform bebas dan tidak menggantikan agensi penerbit atau proses perolehan rasmi.',officialSource:'Buka sumber rasmi ↗',report:'Laporkan data salah atau lapuk',assessment:'Sokongan keputusan',worth:'Wajar dipertimbangkan',review:'Semak dahulu',low:'Tidak disyorkan',profile:'Tambah butiran syarikat',addProfile:'Tambah butiran syarikat untuk penilaian yang lebih relevan.',next:'Langkah seterusnya',confirmEligibility:'Sahkan kelayakan dan pendaftaran',reviewDocs:'Semak dokumen rasmi dan skop',checkBriefing:'Semak keperluan lawatan tapak / taklimat',prepareSubmission:'Sediakan semua dokumen penghantaran',confirmDeadline:'Sahkan tarikh, masa dan kaedah tutup'}
} as const

function fmtDateTime(value:string|null,lang:'en'|'zh'|'ms'){if(!value)return '—';const d=new Date(value);if(Number.isNaN(d.getTime()))return value;return new Intl.DateTimeFormat(lang==='zh'?'zh-CN':lang==='ms'?'ms-MY':'en-MY',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kuching'}).format(d)}
function statusLabel(label:BidAssessment['label'],c:(typeof copy)['en']){return label==='Strong Fit'?c.worth:label==='Low Fit'?c.low:label==='Profile Required'?c.profile:c.review}
function findOfficial(snapshot:OfficialTenderSnapshot,pattern:RegExp){return snapshot.fields.filter(f=>pattern.test(f.label)).map(f=>`${f.label}: ${f.value}`)}

export default function OpportunityDetailView({opportunity,awards,assessment,companyPresent,buyerInfo,buyerLink,pageTerms,snapshot}:{opportunity:Opportunity;awards:OpportunityAward[];assessment:BidAssessment;companyPresent:boolean;buyerInfo:BuyerInfo;buyerLink:BuyerLink;pageTerms:ProcurementTerm[];snapshot:OfficialTenderSnapshot}){
 const {lang}=useI18n();const c=copy[lang] as typeof copy.en
 const today=new Date().toISOString().slice(0,10);const isOpen=!opportunity.closing_date||opportunity.closing_date>=today;const hasAward=awards.length>0
 const eligibility=findOfficial(snapshot,/CIDB|UPKJ|MOF|grade|class|category|head|sub.?head|bumiputera|registration|kelayakan|pendaftaran/i)
 const submission=findOfficial(snapshot,/submit|submission|closing time|address|place|obtain|purchase|document fee|fee|briefing|site visit|taklimat|lawatan|hantar|alamat|bayaran/i)
 const prepare=[c.confirmEligibility,c.reviewDocs,c.checkBriefing,c.prepareSubmission,c.confirmDeadline]
 const assessmentClass=assessment.label==='Strong Fit'?'assessment-strong':assessment.label==='Low Fit'?'assessment-low':assessment.label==='Profile Required'?'assessment-profile':'assessment-consider'
 return <main className="section"><div className="container tender-detail-v2">
  <Link className="source back-link" href="/opportunities">{c.back}</Link>
  <header className="tender-title-block"><div className="eyebrow">{c.eyebrow}</div><h1>{opportunity.title}</h1><div className="tender-head-meta"><span className={`status-pill ${hasAward?'awarded':isOpen?'open':'closed'}`}>{hasAward?c.awarded:isOpen?c.open:c.closed}</span><span>{opportunity.reference??c.notPublished}</span><span>{buyerInfo.display}</span><span>{opportunity.closing_date??'—'}</span></div></header>

  <section className="tender-decision-bar"><div><span className="eyebrow">{c.assessment}</span><strong>{statusLabel(assessment.label,c)}</strong><p>{assessment.summary}</p></div><span className={`assessment-label ${assessmentClass}`}>{statusLabel(assessment.label,c)}</span></section>

  <section className="tender-section"><div className="tender-section-head"><div><div className="eyebrow">{c.officialData}</div><h2>{c.projectInfo}</h2><p>{c.officialFacts}</p></div><ContextInfoDrawer terms={pageTerms}/></div>
   <div className="tender-core-facts"><div><span>{c.buyer}</span><strong>{buyerInfo.display}</strong>{buyerInfo.fullName!==buyerInfo.display&&<small>{buyerInfo.fullName}</small>}</div><div><span>{c.reference}</span><strong>{opportunity.reference??'—'}</strong></div><div><span>{c.market}</span><strong>Sarawak, Malaysia</strong></div><div><span>{c.posted}</span><strong>{opportunity.posted_date??'—'}</strong></div><div><span>{c.closing}</span><strong>{opportunity.closing_date??'—'}</strong></div><div><span>{c.type}</span><strong>{opportunity.opportunity_type}</strong></div></div>
   {snapshot.fields.length?<div className="official-fact-table">{snapshot.fields.map((f,i)=><div key={`${f.label}-${i}`}><span>{f.label}</span><strong>{f.value}</strong></div>)}</div>:<p className="meta">{c.noExtraFacts}</p>}
   <div className="official-document-row"><div><strong>{c.officialDocument}</strong><span>{snapshot.sourceName||c.official}</span></div><OfficialPdfButton sourceUrl={opportunity.source_url} reference={opportunity.reference}/></div>
  </section>

  <section className="tender-section"><div className="tender-section-head"><div><div className="eyebrow">{c.officialData}</div><h2>{c.keyDates}</h2></div></div><div className="key-date-line"><div><span>01</span><strong>{c.published}</strong><b>{opportunity.posted_date??'—'}</b></div><div><span>02</span><strong>{c.deadline}</strong><b>{opportunity.closing_date??'—'}</b></div>{awards.slice(0,1).map(a=><div key={a.id}><span>03</span><strong>{c.awardPublished}</strong><b>{a.award_date??'—'}</b></div>)}</div></section>

  <section className="tender-section"><div className="tender-section-head"><div><div className="eyebrow">{c.officialData}</div><h2>{c.eligibility}</h2><p>{c.eligibilityNote}</p></div></div>{eligibility.length?<ul className="plain-check-list official">{eligibility.map(x=><li key={x}>{x}</li>)}</ul>:<p className="empty-official">{c.notStated}</p>}</section>

  <details className="tender-fold" open><summary><div><span className="eyebrow">{c.officialData}</span><strong>{c.content}</strong><small>{c.contentNote}</small></div><span>＋</span></summary><div className="tender-fold-body">{snapshot.content.length?snapshot.content.map((x,i)=><p className="official-original-copy" key={i}>{x}</p>):<p className="meta">{c.contentFallback}</p>}</div></details>

  <details className="tender-fold"><summary><div><span className="eyebrow">{c.summaryLabel}</span><strong>{c.summary}</strong></div><span>＋</span></summary><div className="tender-fold-body"><p>{c.summaryText.replace('{buyer}',buyerInfo.display)}</p></div></details>

  <details className="tender-fold"><summary><div><span className="eyebrow">{c.prepareLabel}</span><strong>{c.prepare}</strong><small>{c.prepareNote}</small></div><span>＋</span></summary><div className="tender-fold-body"><ul className="plain-check-list">{prepare.map(x=><li key={x}>{x}</li>)}</ul></div></details>

  <details className="tender-fold"><summary><div><span className="eyebrow">{c.officialData}</span><strong>{c.howSubmit}</strong><small>{c.submitNote}</small></div><span>＋</span></summary><div className="tender-fold-body">{submission.length?<ul className="plain-check-list official">{submission.map(x=><li key={x}>{x}</li>)}</ul>:<p className="empty-official">{c.notStated}</p>}</div></details>

  <section className="tender-section buyer-context-line"><div><div className="eyebrow">{c.buyerContext}</div><h2>{buyerInfo.display}</h2><p>{c.buyerContextText}</p></div>{buyerLink&&<Link href={`/buyers/${buyerLink.slug}`} className="source">{c.viewBuyer}</Link>}</section>

  <details className="tender-fold"><summary><div><span className="eyebrow">{c.officialData}</span><strong>{c.timeline}</strong></div><span>＋</span></summary><div className="tender-fold-body"><div className="procurement-timeline"><div className="timeline-item"><span className="timeline-dot complete"/><div><strong>{c.published}</strong><span>{opportunity.posted_date??'—'}</span></div></div><div className="timeline-item"><span className="timeline-dot complete"/><div><strong>{c.deadline}</strong><span>{opportunity.closing_date??'—'}</span></div></div>{awards.map(a=><div className="timeline-item" key={a.id}><span className="timeline-dot complete"/><div><strong>{c.awardPublished}</strong><span>{a.award_date??'—'} · {a.awarded_company}</span></div></div>)}</div></div></details>

  <section className="tender-trust"><div><div className="eyebrow">{c.trust}</div><p>{c.trustText}</p><div className="trust-meta"><span>{c.source}: {snapshot.sourceName||c.official}</span><span>{c.lastChecked}: {fmtDateTime(opportunity.last_checked_at||snapshot.checkedAt,lang)}</span><span>{c.reference}: {opportunity.reference??c.notPublished}</span></div></div><div className="trust-actions"><a href={opportunity.source_url} target="_blank" rel="noreferrer" className="source">{c.officialSource}</a><ReportDataIssue entityId={opportunity.id}/></div></section>

  {!companyPresent&&<div className="decision-action"><span>{c.addProfile}</span><Link className="btn" href="/onboarding">{c.profile}</Link></div>}
  {!hasAward&&<div className="tender-bottom-action"><span className="eyebrow">{c.next}</span><OpportunityPipelineAction opportunityId={opportunity.id}/></div>}
 </div></main>
}
