'use client'
import Link from 'next/link'
import {useI18n} from '@/components/i18n'

const copy={
 en:{desc:'Business intelligence for opportunities, companies and commercial relationships across Borneo.',company:'Company',about:'About',purpose:'Our Purpose',trust:'Trust Center',help:'Help',support:'Support',qa:'Q&A',subscribe:'Subscription',trustData:'Trust & Data',sources:'Data Sources',accuracy:'Data Accuracy',translation:'Translation Notice',legal:'Legal',terms:'Terms of Service',privacy:'Privacy Policy',disclaimer:'Disclaimer',third:'Third-Party & IP',rights:'© 2026 Borneo Business. All rights reserved.',independent:'Independent business intelligence platform. Not affiliated with or endorsed by any government agency.'},
 zh:{desc:'面向婆罗洲商机、企业与商业关系的商业情报平台。',company:'公司',about:'关于我们',purpose:'我们的目的',trust:'信任中心',help:'帮助',support:'Support',qa:'Q&A',subscribe:'订阅',trustData:'信任与数据',sources:'数据来源',accuracy:'数据准确性',translation:'翻译说明',legal:'法律',terms:'服务条款',privacy:'隐私政策',disclaimer:'免责声明',third:'第三方与知识产权',rights:'© 2026 Borneo Business。保留所有权利。',independent:'独立商业情报平台。除非明确说明，与任何政府机构均无隶属或官方背书关系。'},
 ms:{desc:'Risikan perniagaan untuk peluang, syarikat dan hubungan komersial di seluruh Borneo.',company:'Syarikat',about:'Tentang Kami',purpose:'Tujuan Kami',trust:'Pusat Kepercayaan',help:'Bantuan',support:'Sokongan',qa:'Soalan & Jawapan',subscribe:'Langganan',trustData:'Kepercayaan & Data',sources:'Sumber Data',accuracy:'Ketepatan Data',translation:'Notis Terjemahan',legal:'Undang-undang',terms:'Terma Perkhidmatan',privacy:'Dasar Privasi',disclaimer:'Penafian',third:'Pihak Ketiga & IP',rights:'© 2026 Borneo Business. Hak cipta terpelihara.',independent:'Platform risikan perniagaan bebas. Tidak bergabung atau disokong oleh mana-mana agensi kerajaan kecuali dinyatakan.'}
} as const

export default function SiteFooter(){const {lang}=useI18n();const c=copy[lang];return <footer className="footer formal-footer"><div className="container"><div className="footer-grid"><div className="footer-brand"><strong>Borneo Business</strong><p>{c.desc}</p></div><div><strong>{c.company}</strong><Link href="/about">{c.about}</Link><Link href="/purpose">{c.purpose}</Link><Link href="/trust">{c.trust}</Link></div><div><strong>{c.help}</strong><Link href="/support">{c.support}</Link><Link href="/qa">{c.qa}</Link><Link href="/subscribe">{c.subscribe}</Link></div><div><strong>{c.trustData}</strong><Link href="/trust/data-sources">{c.sources}</Link><Link href="/trust/data-accuracy">{c.accuracy}</Link><Link href="/trust/translation">{c.translation}</Link></div><div><strong>{c.legal}</strong><Link href="/legal/terms">{c.terms}</Link><Link href="/legal/privacy">{c.privacy}</Link><Link href="/legal/disclaimer">{c.disclaimer}</Link><Link href="/legal/third-party">{c.third}</Link></div></div><div className="footer-bottom"><span>{c.rights}</span><span>{c.independent}</span></div></div></footer>}
