'use client'

import {useI18n} from '@/components/i18n'

const data={
 en:{title:'Questions & answers',sub:'Quick answers for the things people most often need when using Borneo Business.',groups:[
  {title:'Getting started',items:[['What is Borneo Business?','Borneo Business organizes public procurement and business information so companies can understand opportunities faster and keep the original source close at hand.'],['Do I need an account to view opportunities?','No. Public opportunities and source information can be viewed without an account. A company profile is useful when you want the platform to compare an opportunity with your business.'],['Why should I add company details?','Your capabilities, markets and business goals help Borneo Business show whether an opportunity appears relevant to your company. Official tender eligibility is still determined by the procuring agency.']]},
  {title:'Understanding tenders',items:[['What do CIDB, UPKJ, JKR and other abbreviations mean?','When a common abbreviation appears on an opportunity page, use the small information button on that page. It opens a contextual explanation without leaving the tender.'],['Does Borneo Business decide whether I am legally eligible?','No. We help organize the available information, but registration grade, category, briefing attendance and legal eligibility must be confirmed from the official tender documents.'],['How do I participate in a tender?','Open the opportunity, review the participation section, confirm eligibility, obtain the official documents, follow the procuring agency’s submission instructions and submit directly to that agency.']]},
  {title:'Translation & documents',items:[['Is the translation an official translation?','No. Translation is provided to make the notice easier to understand. The original official notice, reference, dates, qualification codes and tender documents remain authoritative.'],['Can I download the official tender information as PDF?','Where an official PDF is published, Borneo Business can link directly to it. For supported official web notices, an official-source copy can also be prepared for easier reading while preserving the original source link.'],['Why is there sometimes no PDF button?','Some procuring agencies publish the notice only as a web page or require documents to be obtained through a separate process. Borneo Business will not label a generated or incomplete document as an official PDF.']]},
  {title:'Saved opportunities & results',items:[['What happens when I save an opportunity?','It is added to your Saved Opportunities so you can keep the next step, current status and outcome in one place.'],['Where does award information come from?','Award information is shown only when it can be tied to a published public source. If a value is not published, it is shown as Not disclosed rather than estimated.']]}
 ]},
 zh:{title:'常见问题',sub:'整理使用 Borneo Business 时最常遇到的问题，点开即可查看答案。',groups:[
  {title:'开始使用',items:[['Borneo Business 是什么？','Borneo Business 整理公开采购与商业资料，让企业更快看懂商机，同时保留原始来源方便核对。'],['一定要有帐号才能看商机吗？','不用。公开商机与来源资料不登录也可以查看。建立公司资料后，平台才可以把商机和你的公司能力进行对照。'],['为什么要填写公司资料？','公司能力、市场和目标会帮助 Borneo Business 判断某个商机是否与你的公司相关。正式投标资格仍以采购单位公布的规定为准。']]},
  {title:'看懂标案',items:[['CIDB、UPKJ、JKR 等简称是什么意思？','当常见简称出现在商机页面时，点 Buyer 旁边的小 i 按钮，就会从页面上方滑出解释，不需要离开标案页面。'],['Borneo Business 会判断我是否有正式投标资格吗？','不会。平台会整理现有资料，但注册等级、类别、说明会出席要求和法律资格都必须以官方标案文件确认。'],['我要怎么参与投标？','打开商机后先看参与方式，确认资格、取得官方文件，再按照采购单位的提交说明直接向该单位递交。']]},
  {title:'翻译与文件',items:[['平台翻译是正式翻译吗？','不是。翻译只是帮助理解。正式公告、编号、日期、资格代码与投标文件仍以官方原文为准。'],['可以下载官方标案 PDF 吗？','如果官方本身提供 PDF，Borneo Business 会直接提供入口。对于支持的官方网页，也可以生成保留来源链接的官方来源副本，方便阅读。'],['为什么有时没有 PDF？','有些采购单位只提供网页，或要求通过其他方式取得文件。Borneo Business 不会把不完整或自行生成的资料冒充官方 PDF。']]},
  {title:'已保存商机与结果',items:[['保存商机会发生什么？','商机会加入“已保存商机”，你可以记录下一步、当前进度和最后结果。'],['中标资料从哪里来？','只有能够对应到公开来源时才会显示中标资料。如果官方没有公布金额，就会明确显示“未公开”，不会自行估算。']]}
 ]},
 ms:{title:'Soalan & jawapan',sub:'Jawapan ringkas untuk perkara yang paling kerap diperlukan semasa menggunakan Borneo Business.',groups:[
  {title:'Mula menggunakan',items:[['Apakah Borneo Business?','Borneo Business menyusun maklumat perolehan awam dan perniagaan supaya syarikat boleh memahami peluang dengan lebih cepat sambil mengekalkan sumber asal untuk semakan.'],['Adakah saya perlukan akaun untuk melihat peluang?','Tidak. Peluang awam dan maklumat sumber boleh dilihat tanpa akaun. Profil syarikat berguna apabila anda mahu platform membandingkan peluang dengan perniagaan anda.'],['Mengapa saya perlu menambah maklumat syarikat?','Keupayaan, pasaran dan matlamat perniagaan membantu Borneo Business menunjukkan sama ada sesuatu peluang berkaitan dengan syarikat anda. Kelayakan rasmi tetap ditentukan oleh agensi perolehan.']]},
  {title:'Memahami tender',items:[['Apakah maksud singkatan seperti CIDB, UPKJ dan JKR?','Apabila singkatan biasa muncul pada halaman peluang, tekan butang i kecil di sebelah nama pembeli. Penjelasan akan meluncur turun dari bahagian atas tanpa meninggalkan halaman tender.'],['Adakah Borneo Business menentukan kelayakan rasmi saya?','Tidak. Kami menyusun maklumat yang ada, tetapi gred pendaftaran, kategori, kehadiran taklimat dan kelayakan undang-undang mesti disahkan daripada dokumen tender rasmi.'],['Bagaimana saya menyertai tender?','Buka peluang, semak bahagian cara menyertai, sahkan kelayakan, dapatkan dokumen rasmi dan ikut arahan penghantaran agensi berkenaan.']]},
  {title:'Terjemahan & dokumen',items:[['Adakah terjemahan ini rasmi?','Tidak. Terjemahan disediakan untuk membantu pemahaman. Notis asal, nombor rujukan, tarikh, kod kelayakan dan dokumen tender rasmi kekal sebagai rujukan utama.'],['Bolehkah saya memuat turun maklumat tender rasmi sebagai PDF?','Jika PDF rasmi diterbitkan, Borneo Business boleh memaut terus kepadanya. Untuk laman rasmi yang disokong, salinan sumber rasmi juga boleh disediakan sambil mengekalkan pautan asal.'],['Mengapa kadang-kadang tiada butang PDF?','Sesetengah agensi menerbitkan notis hanya sebagai laman web atau memerlukan dokumen diperoleh melalui proses lain. Borneo Business tidak akan melabel dokumen yang dijana atau tidak lengkap sebagai PDF rasmi.']]},
  {title:'Peluang disimpan & keputusan',items:[['Apa berlaku apabila saya menyimpan peluang?','Ia ditambah ke Peluang Disimpan supaya langkah seterusnya, status semasa dan keputusan boleh direkodkan di satu tempat.'],['Dari mana maklumat anugerah diperoleh?','Maklumat anugerah hanya dipaparkan apabila boleh dikaitkan dengan sumber awam yang diterbitkan. Jika nilai tidak diterbitkan, ia dipaparkan sebagai Tidak didedahkan dan bukan dianggarkan.']]}
 ]}
} as const

export default function QAPage(){const {lang}=useI18n();const c=data[lang];return <main className="section"><div className="container policy-container"><div className="eyebrow">Q&A</div><h1>{c.title}</h1><p className="sub">{c.sub}</p><div className="qa-groups">{c.groups.map(group=><section key={group.title}><h2>{group.title}</h2>{group.items.map(([q,a])=><details className="qa-item" key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>)}</div></div></main>}
