import LegalPage from '@/components/legal-page'
export default function Page(){return <LegalPage eyebrow="Legal" title="Privacy Policy" intro="This policy explains the main categories of information Borneo Business processes when people use the platform." note="This product policy is intended to describe current platform practices. It should be reviewed against the final operating entity, jurisdictions and payment/analytics services before commercial launch." sections={[
 {title:'Information you provide',body:['We may process account information such as email address, profile information, company details, capabilities, markets served, opportunity preferences, pipeline activity, referrals and information submitted through correction or support forms.']},
 {title:'Service and device information',body:['We may use necessary cookies or browser storage to maintain authentication, language and interface preferences. Technical logs may be processed for security, reliability and troubleshooting. Additional analytics or advertising technologies, if introduced, will require this policy and any applicable consent mechanism to be updated.']},
 {title:'Why we process information',body:['Information is used to provide accounts and platform features, personalize opportunity discovery, maintain private pipeline records, improve data quality, protect the service and communicate about requested support or account matters.']},
 {title:'Service providers',body:['Infrastructure and software providers may process limited information on our behalf to operate hosting, database, authentication and related technical services. We do not treat those providers as owners of your business profile or private pipeline data.']},
 {title:'Public and private information',body:['Public-source company or organization information may appear in the business intelligence database. Account credentials and private pipeline activity are not intended to be public. Company profile visibility may depend on the feature and information submitted.']},
 {title:'Retention and requests',body:['We retain information for as long as reasonably needed to operate the service, meet legitimate business or legal requirements and resolve disputes. Where applicable, users may request access, correction or deletion of personal information, subject to identity verification and legal retention requirements.']},
 {title:'Security',body:['We use technical and organizational measures intended to protect account and platform data, but no internet service can guarantee absolute security. Users are responsible for keeping account credentials confidential.']},
 {title:'Policy changes',body:['This policy may be updated as Borneo Business adds markets, payments, analytics, new data sources or other services. Material changes should be reflected by an updated effective date and, where appropriate, additional notice.']}
 ]}/>}
