'use client'

import Link from 'next/link'
import {useI18n} from '@/components/i18n'

const base=[
 ['CIDB','Construction Industry Development Board Malaysia'],['UPKJ','Unit Pendaftaran Kontraktor dan Juruperunding'],['MOF','Ministry of Finance Malaysia'],['JKR','Jabatan Kerja Raya / Public Works Department'],['RFQ','Request for Quotation'],['RFP','Request for Proposal'],['Tender','Formal Tender'],['Site Visit','Site Visit / Tender Briefing'],['LOA','Letter of Award'],['Bumiputera','Bumiputera Status / Requirement']
] as const
const text={
 en:{title:'Tender & procurement terms',lead:'A simple reference for common organizations, procurement methods and tender terms. On opportunity pages, the small information button explains abbreviations in context.',notice:'This guide helps with understanding only. Eligibility, registration and submission requirements always come from the latest official tender documents.',back:'Back to opportunities',items:[
 ['Malaysia construction industry regulator. Construction tenders may specify CIDB registration, grade or category.'],['Sarawak contractor and consultant registration system often referenced in state procurement.'],['Malaysia Ministry of Finance. Some federal procurement requires MOF supplier registration or codes.'],['Public Works Department / Jabatan Kerja Raya, a common public works buyer and project agency.'],['A request for suppliers to submit a quotation and basic supporting information.'],['A request for a fuller technical and commercial proposal, not only a price.'],['A formal procurement process with eligibility, documentation, deadlines and a defined submission method.'],['A site visit or briefing. If marked mandatory or compulsory, attendance may affect eligibility.'],['A formal letter notifying that a project or contract has been awarded.'],['A Bumiputera status or participation requirement when explicitly stated by the procuring agency.']]},
 zh:{title:'投标与采购术语指南',lead:'这里简单解释常见机构、采购方式和投标术语。在商机页面遇到简称时，也可以直接点小 i 按钮查看当页说明。',notice:'这份指南只是帮助理解，不是资格认定。能不能投、需要什么注册和文件，一律以采购方最新官方文件为准。',back:'返回商机',items:[
 ['马来西亚建筑工业发展局。建筑项目可能会指定 CIDB 注册、等级或类别。'],['砂拉越承包商与顾问注册体系，州政府采购中经常出现。'],['马来西亚财政部。部分联邦政府采购会要求 MOF 供应商注册或相关代码。'],['公共工程局，常见于公共工程与基础设施项目。'],['询价，通常要求供应商提交报价和基本资料。'],['征求建议书，通常要求较完整的技术方案与商业报价。'],['正式招标程序，通常包含资格、文件、截止时间和指定提交方式。'],['现场勘查／投标说明会。若标示必须参加，缺席可能影响资格。'],['中标通知书，采购方正式通知项目或合约授予结果的文件之一。'],['当采购方明确写出时，可能存在 Bumiputera 资格或参与要求。']]},
 ms:{title:'Panduan istilah tender & perolehan',lead:'Rujukan ringkas untuk organisasi, kaedah perolehan dan istilah tender biasa. Pada halaman peluang, butang i kecil juga menerangkan singkatan mengikut konteks.',notice:'Panduan ini hanya membantu pemahaman. Kelayakan, pendaftaran dan syarat penghantaran sentiasa ditentukan oleh dokumen tender rasmi terkini.',back:'Kembali ke peluang',items:[
 ['Badan kawal selia industri pembinaan Malaysia. Tender pembinaan mungkin menetapkan pendaftaran, gred atau kategori CIDB.'],['Sistem pendaftaran kontraktor dan perunding Sarawak yang kerap dirujuk dalam perolehan negeri.'],['Kementerian Kewangan Malaysia. Sesetengah perolehan persekutuan memerlukan pendaftaran atau kod pembekal MOF.'],['Jabatan Kerja Raya / Public Works Department, agensi biasa untuk projek kerja awam dan infrastruktur.'],['Permintaan kepada pembekal untuk mengemukakan sebut harga dan maklumat asas.'],['Permintaan untuk cadangan teknikal dan komersial yang lebih lengkap, bukan harga sahaja.'],['Proses perolehan rasmi dengan syarat kelayakan, dokumen, tarikh tutup dan kaedah penghantaran.'],['Lawatan tapak atau taklimat tender. Jika diwajibkan, kehadiran boleh mempengaruhi kelayakan.'],['Surat rasmi yang memaklumkan sesuatu projek atau kontrak telah dianugerahkan.'],['Syarat status atau penyertaan Bumiputera apabila dinyatakan dengan jelas oleh agensi perolehan.']]}
} as const

export default function ProcurementGuidePage(){const {lang}=useI18n();const c=text[lang];return <main className="section"><div className="container policy-container"><div className="eyebrow">PROCUREMENT GUIDE</div><h1>{c.title}</h1><p className="sub policy-lead">{c.lead}</p><div className="policy-notice"><strong>{lang==='zh'?'重要：':lang==='ms'?'Penting:':'Important:'}</strong> {c.notice}</div><div className="term-directory">{base.map((x,i)=><article className="term-entry" id={x[0].toLowerCase().replace(' ','-')} key={x[0]}><div className="term-code">{x[0]}</div><div><h2>{x[0]} <span>({x[1]})</span></h2><p>{c.items[i][0]}</p></div></article>)}</div><div className="guide-bottom"><Link className="btn" href="/opportunities">{c.back}</Link></div></div></main>}
