'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import MemberShell from '@/components/member-shell'
import { supabase } from '@/lib/browser-supabase'
import {useI18n} from '@/components/i18n'

type Company = { name:string; description:string|null; capabilities:string[]; markets:string[]; opportunity_markets:string[]; looking_for:string[] }
const copy={
 en:{eyebrow:'GET STARTED',title:'Set up your company',sub:'Complete the basic information first. Borneo Business will then show opportunities that are more relevant to your company.',loading:'Loading…',complete:'complete',how:'How to use Borneo Business',howText:'Add your company information, browse public opportunities, check whether the project suits your business, save the ones you want to follow and verify all formal requirements on the official source before submitting.',steps:[['Add your company details','Company name, description, base and website help the platform understand what business you are in.','Edit Company Profile'],['Choose what your company can deliver','Select the capabilities your company can actually provide.','Set Capabilities'],['Choose where you want business','Select the markets where your company is willing to take projects.','Choose Markets'],['Tell us what you are looking for','For example tenders, projects, customers or business partners.','Set Business Goals'],['Save your first opportunity','Open an opportunity, check whether it is worth your time and choose Save Opportunity if you want to keep following it.','Browse Opportunities']],terms:'Need help with tender terms?',termsText:'Common procurement terms are explained in plain language when they appear on a project page.',openTerms:'Open Tender Guide',openMy:'Open My Opportunities',finish:'Finish setup',skip:'Skip for now',review:'Review'},
 zh:{eyebrow:'开始使用',title:'设置你的公司资料',sub:'先完成基本资料，Borneo Business 才能把更相关的商机整理给你。',loading:'加载中…',complete:'已完成',how:'怎么使用 Borneo Business',howText:'填写公司资料、浏览公开商机、判断项目是否适合、保存想继续跟进的商机，并在正式提交前核对官方要求。',steps:[['填写公司资料','公司名称、简介、所在地和网站可以帮助平台理解你的业务。','编辑公司资料'],['选择公司能提供的能力','只选择公司实际上可以交付的产品或服务能力。','设置公司能力'],['选择想开发的市场','选择公司愿意承接项目的市场。','选择市场'],['告诉我们你正在寻找什么','例如标案、项目、客户或合作伙伴。','设置业务目标'],['保存第一个商机','打开商机，判断是否值得跟进；想继续关注时就选择“保存商机”。','浏览商机']],terms:'看不懂投标术语？',termsText:'常见采购术语会在项目页面出现时提供简单说明。',openTerms:'打开投标指南',openMy:'打开我的商机',finish:'完成设置',skip:'暂时跳过',review:'查看'},
 ms:{eyebrow:'MULA',title:'Sediakan profil syarikat anda',sub:'Lengkapkan maklumat asas dahulu. Borneo Business kemudian boleh menunjukkan peluang yang lebih berkaitan dengan syarikat anda.',loading:'Memuatkan…',complete:'selesai',how:'Cara menggunakan Borneo Business',howText:'Tambah maklumat syarikat, lihat peluang awam, semak sama ada projek sesuai, simpan peluang yang mahu diikuti dan sahkan semua keperluan rasmi sebelum menghantar.',steps:[['Tambah maklumat syarikat','Nama syarikat, penerangan, lokasi dan laman web membantu platform memahami perniagaan anda.','Edit Profil Syarikat'],['Pilih apa yang syarikat boleh lakukan','Pilih hanya keupayaan yang benar-benar boleh disediakan oleh syarikat.','Tetapkan Keupayaan'],['Pilih pasaran sasaran','Pilih pasaran tempat syarikat bersedia mengambil projek.','Pilih Pasaran'],['Beritahu apa yang anda cari','Contohnya tender, projek, pelanggan atau rakan niaga.','Tetapkan Matlamat'],['Simpan peluang pertama anda','Buka peluang, semak sama ada berbaloi dan pilih Simpan Peluang jika mahu terus mengikuti.','Lihat Peluang']],terms:'Perlukan bantuan dengan istilah tender?',termsText:'Istilah perolehan biasa diterangkan dalam bahasa mudah apabila ia muncul pada halaman projek.',openTerms:'Buka Panduan Tender',openMy:'Buka Peluang Saya',finish:'Selesai persediaan',skip:'Langkau dahulu',review:'Semak'}
} as const

export default function GuidePage(){
  const {lang}=useI18n();const c=copy[lang]
  const [company,setCompany]=useState<Company|null>(null);const [savedCount,setSavedCount]=useState(0);const [finished,setFinished]=useState(false);const [loading,setLoading]=useState(true)
  useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser(); if(!user){setLoading(false);return}const [{data:co},{count},{data:p}]=await Promise.all([supabase.from('companies').select('name,description,capabilities,markets,opportunity_markets,looking_for').eq('owner_id',user.id).limit(1).maybeSingle(),supabase.from('pipeline_items').select('id',{count:'exact',head:true}).eq('user_id',user.id),supabase.from('profiles').select('onboarding_completed').eq('id',user.id).maybeSingle()]);setCompany(co as Company|null);setSavedCount(count||0);setFinished(Boolean(p?.onboarding_completed));setLoading(false)})()},[])
  const checks=useMemo(()=>({identity:Boolean(company?.name&&company?.description),capability:Boolean(company?.capabilities?.length),market:Boolean(company?.opportunity_markets?.length),goal:Boolean(company?.looking_for?.length),saved:savedCount>0}),[company,savedCount]);const completed=Object.values(checks).filter(Boolean).length
  async function finish(){const {data:{user}}=await supabase.auth.getUser();if(!user)return;await supabase.from('profiles').update({onboarding_completed:true}).eq('id',user.id);setFinished(true);window.location.assign('/dashboard')}
  const values=Object.values(checks)
  return <MemberShell><main className="member-page"><div className="container narrow-wide"><div className="member-heading"><div><div className="eyebrow">{c.eyebrow}</div><h1 className="page-title">{c.title}</h1><p className="sub">{c.sub}</p></div><div className="verified-badge">{loading?c.loading:`${completed}/5 ${c.complete}`}</div></div><section className="panel" style={{marginBottom:18}}><div className="panel-title">{c.how}</div><p className="sub" style={{marginBottom:0}}>{c.howText}</p></section><div style={{display:'grid',gap:12}}>{c.steps.map((s,i)=><GuideStep key={s[0]} no={`0${i+1}`} done={values[i]} title={s[0]} text={s[1]} href={i===4?'/opportunities':'/profile'} action={s[2]} review={c.review}/>)}</div><section className="panel" style={{marginTop:18}}><div className="panel-title">{c.terms}</div><p className="meta">{c.termsText}</p><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:12}}><Link className="btn" href="/procurement-guide">{c.openTerms}</Link><button className="btn primary" onClick={finish}>{finished?c.openMy:c.finish}</button><Link className="btn" href="/dashboard">{c.skip}</Link></div></section></div></main></MemberShell>
}
function GuideStep({no,done,title,text,href,action,review}:{no:string;done:boolean;title:string;text:string;href:string;action:string;review:string}){return <section className="panel" style={{display:'flex',gap:16,alignItems:'center',flexWrap:'wrap'}}><div style={{width:46,height:46,flex:'0 0 46px',borderRadius:8,border:'1px solid #DDE4EA',display:'grid',placeItems:'center',fontWeight:800,color:done?'#163B65':'#647181'}}>{done?'✓':no}</div><div style={{flex:'1 1 300px',minWidth:0}}><div className="panel-title" style={{marginBottom:5}}>{title}</div><p className="meta" style={{margin:0}}>{text}</p></div><Link className={done?'btn':'btn primary'} href={href}>{done?review:action}</Link></section>}
