'use client'

import Link from 'next/link'
import {useI18n} from '@/components/i18n'

const copy={
 en:{title:'Choose how your company tracks procurement',sub:'Public tender data remains accessible. Paid plans focus on saving time through tracking, alerts, buyer history, award history and export tools — not AI branding.',payments:'Payments',paymentNote:'Paid subscriptions are planned to use Stripe for recurring billing. Checkout is not enabled yet, so no payment can be charged from this page today.',question:'Subscription question',plans:[
  {name:'Free',tag:'For browsing the Sarawak market',price:'RM0',features:['Browse public opportunities','Search by keyword, buyer and location','Filter open and closing-soon tenders','View official source links','View basic buyer and award records'],cta:'Browse opportunities',href:'/opportunities'},
  {name:'Professional',tag:'For companies actively bidding',price:'Coming soon',features:['Saved tender watchlist','New tender alerts','Buyer procurement history','Award and winning-company history','Advanced filters and deadline tracking','CSV export'],cta:'Ask about Professional',href:'/support'},
  {name:'Business',tag:'For teams managing many bids',price:'Coming soon',features:['Everything in Professional','Team watchlists','Shared tender tracking','Buyer and competitor monitoring','Exports and reporting','Priority support'],cta:'Ask about Business',href:'/support'}]},
 zh:{title:'选择适合公司的标案追踪方式',sub:'公开标案资料继续开放查看。付费价值集中在追踪、通知、采购方历史、中标历史与导出工具，先解决企业每天找标和跟标所花的时间。',payments:'付款',paymentNote:'未来付费订阅计划使用 Stripe 进行周期付款。目前尚未开放结帐，因此这个页面不会产生任何收费。',question:'订阅问题',plans:[
  {name:'Free',tag:'适合浏览砂拉越市场',price:'RM0',features:['浏览公开商机','按关键字、采购方与地区搜索','筛选开放中与即将截止标案','查看官方来源','查看基础采购方与中标记录'],cta:'浏览商机',href:'/opportunities'},
  {name:'Professional',tag:'适合持续参与投标的企业',price:'即将推出',features:['标案 Watchlist','新标案通知','采购方采购历史','中标与得标公司历史','进阶筛选与截止追踪','CSV 导出'],cta:'咨询 Professional',href:'/support'},
  {name:'Business',tag:'适合同时管理多个标案的团队',price:'即将推出',features:['包含 Professional 全部功能','团队 Watchlist','共同跟进标案','采购方与竞争公司监测','导出与报表','优先支持'],cta:'咨询 Business',href:'/support'}]},
 ms:{title:'Pilih cara syarikat menjejak perolehan',sub:'Data tender awam kekal boleh diakses. Nilai pelan berbayar tertumpu pada penjejakan, notifikasi, sejarah pembeli, sejarah anugerah dan eksport — bukan penjenamaan AI.',payments:'Pembayaran',paymentNote:'Langganan berbayar dirancang menggunakan Stripe untuk bil berulang. Checkout belum diaktifkan, jadi tiada bayaran boleh dikenakan dari halaman ini sekarang.',question:'Soalan langganan',plans:[
  {name:'Free',tag:'Untuk meneroka pasaran Sarawak',price:'RM0',features:['Lihat peluang awam','Cari mengikut kata kunci, pembeli dan lokasi','Tapis tender terbuka dan hampir tutup','Buka sumber rasmi','Lihat rekod asas pembeli dan anugerah'],cta:'Lihat peluang',href:'/opportunities'},
  {name:'Professional',tag:'Untuk syarikat yang aktif membida',price:'Akan datang',features:['Watchlist tender tersimpan','Notifikasi tender baharu','Sejarah perolehan pembeli','Sejarah anugerah dan syarikat pemenang','Penapis lanjutan dan penjejakan tarikh tutup','Eksport CSV'],cta:'Tanya tentang Professional',href:'/support'},
  {name:'Business',tag:'Untuk pasukan yang mengurus banyak bidaan',price:'Akan datang',features:['Semua dalam Professional','Watchlist pasukan','Penjejakan tender bersama','Pemantauan pembeli dan pesaing','Eksport dan laporan','Sokongan keutamaan'],cta:'Tanya tentang Business',href:'/support'}]}
} as const

export default function SubscribePage(){const {lang}=useI18n();const c=copy[lang];return <main className="section"><div className="container"><div className="subscribe-head"><div className="eyebrow">SUBSCRIPTION</div><h1 className="page-title">{c.title}</h1><p className="sub">{c.sub}</p></div><div className="plan-grid">{c.plans.map((p,i)=><section className={`plan-card ${i===1?'featured':''}`} key={p.name}><div><div className="plan-name">{p.name}</div><div className="meta">{p.tag}</div><div className="plan-price">{p.price}</div></div><ul>{p.features.map(f=><li key={f}>{f}</li>)}</ul><Link className={`btn full ${i===1?'primary':''}`} href={p.href}>{p.cta}</Link></section>)}</div><section className="panel billing-note"><div><div className="panel-title">{c.payments}</div><p className="meta">{c.paymentNote}</p></div><Link className="source" href="/support">{c.question} →</Link></section></div></main>}
