'use client'

import Link from 'next/link'
import {useI18n} from '@/components/i18n'

const copy={
 en:{title:'Choose how your company uses Borneo Business',sub:'Public information stays easy to access. Paid plans are intended for companies that want deeper organization, tracking and business workflow tools.',payments:'Payments',paymentNote:'Paid subscriptions are planned to use Stripe for recurring billing. Checkout is not enabled yet, so no payment can be charged from this page today.',question:'Subscription question',plans:[
  {name:'Free',tag:'For exploring the market',price:'RM0',features:['Browse public opportunities','View buyers and published awards','Open official source links','Basic translation access','Contextual abbreviation help'],cta:'Browse opportunities',href:'/opportunities'},
  {name:'Professional',tag:'For active business development',price:'Coming soon',features:['Company-based opportunity assessment','Saved Opportunities tracking','Official document shortcuts','Extended buyer and award history','Opportunity notifications','Priority support'],cta:'Ask about Professional',href:'/support'},
  {name:'Business',tag:'For teams handling multiple opportunities',price:'Coming soon',features:['Everything in Professional','Team access','Shared opportunity tracking','Exports and reporting','Company-level activity overview','Priority support'],cta:'Ask about Business',href:'/support'}]},
 zh:{title:'选择适合公司的使用方式',sub:'公开资料继续保持容易查看。付费方案主要提供更完整的整理、跟进和企业使用功能。',payments:'付款',paymentNote:'未来付费订阅计划使用 Stripe 进行周期付款。目前尚未开放结帐，因此这个页面不会产生任何收费。',question:'订阅问题',plans:[
  {name:'Free',tag:'适合查看市场与公开商机',price:'RM0',features:['浏览公开商机','查看采购方与公开中标资料','打开官方来源','基础翻译','页面简称说明'],cta:'浏览商机',href:'/opportunities'},
  {name:'Professional',tag:'适合主动开发业务的企业',price:'即将推出',features:['根据公司资料判断商机','保存并跟进商机','官方文件快捷入口','更多采购方与中标历史','商机通知','优先支持'],cta:'咨询 Professional',href:'/support'},
  {name:'Business',tag:'适合同时处理多个商机的团队',price:'即将推出',features:['包含 Professional 全部功能','团队帐号','共同跟进商机','导出与报表','公司层级活动总览','优先支持'],cta:'咨询 Business',href:'/support'}]},
 ms:{title:'Pilih cara syarikat anda menggunakan Borneo Business',sub:'Maklumat awam kekal mudah diakses. Pelan berbayar ditujukan kepada syarikat yang memerlukan penyusunan, penjejakan dan aliran kerja perniagaan yang lebih lengkap.',payments:'Pembayaran',paymentNote:'Langganan berbayar dirancang menggunakan Stripe untuk bil berulang. Checkout belum diaktifkan, jadi tiada bayaran boleh dikenakan dari halaman ini sekarang.',question:'Soalan langganan',plans:[
  {name:'Free',tag:'Untuk meneroka pasaran',price:'RM0',features:['Lihat peluang awam','Lihat pembeli dan anugerah yang diterbitkan','Buka pautan sumber rasmi','Akses terjemahan asas','Bantuan singkatan mengikut halaman'],cta:'Lihat peluang',href:'/opportunities'},
  {name:'Professional',tag:'Untuk pembangunan perniagaan aktif',price:'Akan datang',features:['Penilaian peluang berdasarkan syarikat','Jejak peluang yang disimpan','Pintasan dokumen rasmi','Sejarah pembeli dan anugerah yang lebih luas','Notifikasi peluang','Sokongan keutamaan'],cta:'Tanya tentang Professional',href:'/support'},
  {name:'Business',tag:'Untuk pasukan yang mengurus banyak peluang',price:'Akan datang',features:['Semua dalam Professional','Akses pasukan','Penjejakan peluang bersama','Eksport dan laporan','Gambaran aktiviti syarikat','Sokongan keutamaan'],cta:'Tanya tentang Business',href:'/support'}]}
} as const

export default function SubscribePage(){const {lang}=useI18n();const c=copy[lang];return <main className="section"><div className="container"><div className="subscribe-head"><div className="eyebrow">SUBSCRIPTION</div><h1 className="page-title">{c.title}</h1><p className="sub">{c.sub}</p></div><div className="plan-grid">{c.plans.map((p,i)=><section className={`plan-card ${i===1?'featured':''}`} key={p.name}><div><div className="plan-name">{p.name}</div><div className="meta">{p.tag}</div><div className="plan-price">{p.price}</div></div><ul>{p.features.map(f=><li key={f}>{f}</li>)}</ul><Link className={`btn full ${i===1?'primary':''}`} href={p.href}>{p.cta}</Link></section>)}</div><section className="panel billing-note"><div><div className="panel-title">{c.payments}</div><p className="meta">{c.paymentNote}</p></div><Link className="source" href="/support">{c.question} →</Link></section></div></main>}
