import Link from 'next/link'

const plans=[
  {name:'Free',tag:'For exploring the market',price:'RM0',features:['Browse public opportunities','View buyers and published awards','Open official source links','Basic translation access','Contextual abbreviation help'],cta:'Current public access',href:'/opportunities'},
  {name:'Professional',tag:'For active business development',price:'Coming soon',features:['Company-based opportunity assessment','Saved Opportunities tracking','Official document shortcuts','Extended buyer and award history','Opportunity notifications','Priority support'],cta:'Ask about Professional',href:'/support'},
  {name:'Business',tag:'For teams handling multiple opportunities',price:'Coming soon',features:['Everything in Professional','Team access','Shared opportunity tracking','Exports and reporting','Company-level activity overview','Priority support'],cta:'Ask about Business',href:'/support'},
]

export default function SubscribePage(){return <main className="section"><div className="container"><div className="subscribe-head"><div className="eyebrow">SUBSCRIPTION</div><h1 className="page-title">Choose how your company uses Borneo Business</h1><p className="sub">Public information stays easy to access. Paid plans are intended for companies that want deeper organization, tracking and business workflow tools.</p></div><div className="plan-grid">{plans.map((p,i)=><section className={`plan-card ${i===1?'featured':''}`} key={p.name}><div><div className="plan-name">{p.name}</div><div className="meta">{p.tag}</div><div className="plan-price">{p.price}</div></div><ul>{p.features.map(f=><li key={f}>{f}</li>)}</ul><Link className={`btn full ${i===1?'primary':''}`} href={p.href}>{p.cta}</Link></section>)}</div><section className="panel billing-note"><div><div className="panel-title">Payments</div><p className="meta">Paid subscriptions are planned to use Stripe for recurring billing. Checkout is not enabled yet, so no payment can be charged from this page today.</p></div><Link className="source" href="/support">Subscription question →</Link></section></div></main>}
