import LegalPage from '@/components/legal-page'
export default function Page(){return <LegalPage eyebrow="Legal" title="Terms of Service" intro="These terms set the basic rules for using Borneo Business and its business intelligence features." note="These terms are a product-ready baseline and should be reviewed against the final operating entity, governing law, billing model and commercial launch jurisdiction before paid subscriptions are activated." sections={[
 {title:'Using the service',body:['You may use Borneo Business for lawful business research, opportunity discovery, company intelligence and related commercial activities. You must not use the service to violate law, impersonate another party, interfere with platform operation or attempt unauthorized access to accounts or systems.']},
 {title:'Accounts',body:['You are responsible for information submitted through your account and for maintaining the confidentiality of your credentials. We may restrict or suspend access where reasonably necessary to address security, abuse, fraud or material breach of these terms.']},
 {title:'Business intelligence',body:['Opportunity records, summaries, translations, matches, classifications and relationship insights are informational tools. They do not create a tender invitation, guarantee eligibility or replace the issuing organization and its official documents.']},
 {title:'User and company information',body:['You should have the right to submit information you provide to the platform. Public-source company information may also be compiled independently. Requests to correct materially inaccurate information may be reviewed under our data-accuracy process.']},
 {title:'Intellectual property',body:['Use of Borneo Business does not transfer ownership of our software, branding, interface, proprietary organization or original analytical content. Third-party source material and trademarks remain subject to their respective rights.']},
 {title:'Service changes',body:['We may add, modify or discontinue features, data sources and market coverage as the product develops. Where paid services are introduced, applicable pricing, renewal, cancellation and refund terms should be presented before purchase.']},
 {title:'No guarantee of outcome',body:['The service does not guarantee that a user will qualify for, win or profit from an opportunity, introduction or commercial relationship. Business decisions and submissions remain the responsibility of the user.']},
 {title:'Changes to terms',body:['We may update these terms as the service develops. Material changes should be reflected by a new effective date and, where appropriate, notice to affected users. Continued use after an applicable change may constitute acceptance where permitted by law.']}
 ]}/>}
