import Link from 'next/link'
import { notFound } from 'next/navigation'
import { getOpportunityAwards, getOpportunityById } from '@/lib/data'
import { assessBid, type CompanyProfile } from '@/lib/matching'
import { createServerSupabase } from '@/lib/supabase-server'
import { buyerDisplayName, contextualTerms } from '@/lib/procurement-terms'
import ContextInfoDrawer from '@/components/context-info-drawer'
import OpportunityPipelineAction from '@/components/opportunity-pipeline-action'
import OpportunityTranslation from '@/components/opportunity-translation'
import ReportDataIssue from '@/components/report-data-issue'

function plainSummary(title:string,buyer:string){const t=title.toLowerCase();if(t.includes('maintenance')||t.includes('penyelenggaraan')||t.includes('repair')||t.includes('baikpulih'))return `A public procurement project from ${buyer} for maintenance, repair or upgrading work described in the official notice.`;if(t.includes('supply')||t.includes('membekal')||t.includes('delivery'))return `A public supply opportunity from ${buyer}. The selected vendor is expected to supply and/or deliver the items described in the official tender documents.`;if(t.includes('construction')||t.includes('pembinaan')||t.includes('membina'))return `A public works project from ${buyer} involving construction or infrastructure work. Contractor eligibility and site requirements must be checked on the official notice.`;return `A public procurement opportunity issued by ${buyer}. This page simplifies the key information so you can decide whether it is worth opening the full official notice.`}
function likelyNeeds(title:string,industry:string|null){const t=title.toLowerCase(),needs:string[]=[];if(t.includes('maintenance')||t.includes('repair')||t.includes('baikpulih'))needs.push('Relevant maintenance / repair capability');if(t.includes('construction')||t.includes('pembinaan')||t.includes('membina')||t.includes('road')||t.includes('jalan'))needs.push('Qualified contractor / civil works capability');if(t.includes('supply')||t.includes('membekal'))needs.push('Product supply and delivery capability');if(industry)needs.push(`${industry} experience or related capability`);needs.push('Eligibility, registration and documents stated in the official tender notice');return Array.from(new Set(needs)).slice(0,4)}
function money(value:number|null,currency:string){if(value==null)return 'Not disclosed';try{return new Intl.NumberFormat('en-MY',{style:'currency',currency,maximumFractionDigits:2}).format(value)}catch{return `${currency} ${value.toLocaleString()}`}}
function dateTime(value:string|null){if(!value)return 'Not available';const d=new Date(value);if(Number.isNaN(d.getTime()))return value;return new Intl.DateTimeFormat('en-MY',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kuching'}).format(d)}
function displayAssessment(label:string){if(label==='Strong Fit')return 'Worth considering';if(label==='Consider')return 'Review first';if(label==='Low Fit')return 'Not recommended';return 'Add company details'}

export default async function OpportunityDetailPage({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const opportunity=await getOpportunityById(id);if(!opportunity||opportunity.region!=='Sarawak')notFound();const awards=await getOpportunityAwards(id);const isOpen=!opportunity.closing_date||opportunity.closing_date>=new Date().toISOString().slice(0,10);const hasAward=awards.length>0;const needs=likelyNeeds(opportunity.title,opportunity.industry);const buyerInfo=buyerDisplayName(opportunity.buyer);const pageTerms=contextualTerms({buyer:opportunity.buyer,title:opportunity.title,reference:opportunity.reference});let company:CompanyProfile|null=null;try{const supabase=await createServerSupabase();const {data:{user}}=await supabase.auth.getUser();if(user){const {data}=await supabase.from('companies').select('region,capabilities,markets,opportunity_markets,looking_for').eq('owner_id',user.id).order('created_at',{ascending:true}).limit(1).maybeSingle();if(data)company={region:data.region,capabilities:data.capabilities??[],markets:data.markets??[],opportunity_markets:data.opportunity_markets??[],looking_for:data.looking_for??[]}}}catch{}
 const assessment=assessBid(opportunity,company);const assessmentClass=assessment.label==='Strong Fit'?'assessment-strong':assessment.label==='Low Fit'?'assessment-low':assessment.label==='Profile Required'?'assessment-profile':'assessment-consider';const assessmentText=displayAssessment(assessment.label);const contactText='Applications and official instructions must be taken from the public procurement notice.';const beforeBid=['Confirm eligibility on the official notice.','Check compulsory site visit or briefing requirements.','Review the official scope and documents.','Confirm closing time and submission method.'];
 return <main className="section"><div className="container detail-layout"><section><Link className="source back-link" href="/opportunities">← Back to opportunities</Link><div className="eyebrow">PUBLIC PROCUREMENT · SARAWAK</div><h1 className="detail-title">{opportunity.title}</h1><div className="detail-tags"><span className={`status-pill ${hasAward?'awarded':isOpen?'open':'closed'}`}>{hasAward?'Awarded':isOpen?'Open':'Closed'}</span><span className="tag">{opportunity.industry??'General'}</span></div>
 <section className="decision-card"><div className="decision-head"><div><div className="eyebrow">IS THIS WORTH YOUR TIME?</div><h2>Should your company pursue this opportunity?</h2></div><span className={`assessment-label ${assessmentClass}`}>{assessmentText}</span></div><p className="decision-summary">{assessment.summary}</p><div className="assessment-table">{assessment.items.map(item=><div className="assessment-row" key={item.label}><span className={`assessment-mark ${item.status}`}>{item.status==='positive'?'✓':item.status==='negative'?'×':item.status==='warning'?'△':'—'}</span><strong>{item.label}</strong><span>{item.detail}</span></div>)}</div>{!company&&<div className="decision-action"><span>Add company details for a more relevant assessment.</span><Link className="btn" href="/onboarding">Add company details</Link></div>}</section>
 <div className="evidence-strip"><div><span>SOURCE</span><strong>Official public record</strong></div><div><span>LAST CHECKED</span><strong>{dateTime(opportunity.last_checked_at)}</strong></div><div><span>REFERENCE</span><strong>{opportunity.reference??'Not published'}</strong></div></div>
 <section className="info-section"><div className="info-section-head"><div><span className="eyebrow">INFORMATION</span><h2>Project information</h2></div><ContextInfoDrawer terms={pageTerms} sourceUrl={opportunity.source_url} reference={opportunity.reference}/></div><div className="detail-grid"><div><span>Buyer / agency</span><strong>{buyerInfo.display}</strong></div><div><span>Reference</span><strong>{opportunity.reference??'—'}</strong></div><div><span>Market</span><strong>Sarawak, Malaysia</strong></div><div><span>Posted</span><strong>{opportunity.posted_date??'—'}</strong></div><div><span>Closing</span><strong>{opportunity.closing_date??'—'}</strong></div><div><span>Type</span><strong>{opportunity.opportunity_type}</strong></div></div></section>
 <div className="detail-sections"><details><summary>Eligibility & registration <span>+</span></summary><div><p>Confirm registrations, grades, categories and mandatory briefings against the official document in Information.</p></div></details><details><summary>How to participate <span>+</span></summary><div><ol className="participation-steps"><li><strong>Confirm eligibility.</strong></li><li><strong>Review the official document.</strong></li><li><strong>Prepare the required submission.</strong></li><li><strong>Submit directly to the procuring agency.</strong></li></ol></div></details><details><summary>Translation <span>+</span></summary><div><div className="translation-notice"><strong>For understanding only.</strong> Official documents remain authoritative.</div><OpportunityTranslation opportunityId={opportunity.id} summary={plainSummary(opportunity.title,opportunity.buyer)} needs={needs} contactText={contactText} beforeBid={beforeBid}/></div></details><details><summary>Project timeline <span>+</span></summary><div><div className="procurement-timeline"><div className="timeline-item"><span className="timeline-dot complete"/><div><strong>Published</strong><span>{opportunity.posted_date??'Date not available'}</span></div></div><div className="timeline-item"><span className="timeline-dot complete"/><div><strong>Closing</strong><span>{opportunity.closing_date??'Not available'}</span></div></div>{hasAward?awards.map(a=><div className="timeline-item" key={a.id}><span className="timeline-dot complete"/><div><strong>Award published</strong><span>{a.award_date??'Date not disclosed'} · {a.awarded_company}</span><small>{money(a.awarded_value,a.currency)}</small></div></div>):null}</div></div></details><details><summary>Source & data notes <span>+</span></summary><div><p>Project facts are indexed from the linked public procurement source. Platform assessment is separate from official eligibility.</p><ReportDataIssue entityId={opportunity.id}/></div></details></div>
 </section><aside className="detail-aside"><div className="sticky-panel simple-aside"><div className="eyebrow">NEXT STEP</div><h2>{hasAward?'Award published':assessmentText}</h2><p className="meta">{assessment.summary}</p>{!hasAward&&<OpportunityPipelineAction opportunityId={opportunity.id}/>}<div className="aside-trust">Official document and source are available from the Information button.</div></div></aside></div></main>
}
