'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import MemberShell from '@/components/member-shell'
import { supabase } from '@/lib/browser-supabase'
import { matchOpportunity, type CompanyProfile } from '@/lib/matching'
import type { Opportunity } from '@/lib/data'
import {useI18n} from '@/components/i18n'

type CompanyRow = CompanyProfile & { id: string; name: string; website: string | null; description: string | null; brands: string[]; looking_for: string[] }
type PipelineRow = { id: string; opportunity_id: string | null; stage: string; deal_value: number | null }
const copy={
 en:{eyebrow:'My opportunities',suffix:'opportunities',title:'My Opportunities',sub:'Launch focus is Sarawak. Your wider Borneo market preferences are saved for future expansion.',edit:'Edit company profile',loading:'Loading opportunities…',finish:'Finish your company profile',finishText:'Add capabilities and target markets so Borneo Business can compare opportunities with your company.',complete:'Complete profile',matches:'Relevant Sarawak opportunities',high:'Higher relevance',saved:'Saved opportunities',won:'Won business recorded',section:'Most relevant',recommended:'Recommended Sarawak projects',browse:'Browse all opportunities',none:'No relevant opportunities yet',noneText:'Add more company capabilities or target markets.',profileMatch:'profile relevance',official:'Official source',closing:'Closing',view:'View project',save:'Save Opportunity',savedButton:'Saved'},
 zh:{eyebrow:'我的商机',suffix:'商机',title:'我的商机',sub:'目前先聚焦砂拉越。你选择的其他婆罗洲市场会保留，未来扩展时继续使用。',edit:'编辑公司资料',loading:'正在加载商机…',finish:'请先完成公司资料',finishText:'填写公司能力和目标市场后，Borneo Business 才能把商机与你的公司进行对照。',complete:'完成公司资料',matches:'相关的砂拉越商机',high:'较高相关度',saved:'已保存商机',won:'已记录赢标金额',section:'最相关',recommended:'建议优先查看的砂拉越项目',browse:'浏览全部商机',none:'目前还没有相关商机',noneText:'可以增加公司能力或调整目标市场。',profileMatch:'公司相关度',official:'官方来源',closing:'截止日期',view:'查看项目',save:'保存商机',savedButton:'已保存'},
 ms:{eyebrow:'Peluang saya',suffix:'peluang',title:'Peluang Saya',sub:'Fokus pelancaran ialah Sarawak. Pilihan pasaran Borneo lain disimpan untuk pengembangan akan datang.',edit:'Edit profil syarikat',loading:'Memuatkan peluang…',finish:'Lengkapkan profil syarikat anda',finishText:'Tambah keupayaan dan pasaran sasaran supaya Borneo Business boleh membandingkan peluang dengan syarikat anda.',complete:'Lengkapkan profil',matches:'Peluang Sarawak berkaitan',high:'Relevan lebih tinggi',saved:'Peluang disimpan',won:'Nilai kemenangan direkodkan',section:'Paling berkaitan',recommended:'Projek Sarawak yang disyorkan',browse:'Lihat semua peluang',none:'Belum ada peluang berkaitan',noneText:'Tambah keupayaan syarikat atau pasaran sasaran.',profileMatch:'relevan dengan profil',official:'Sumber rasmi',closing:'Tarikh tutup',view:'Lihat projek',save:'Simpan Peluang',savedButton:'Disimpan'}
} as const

export default function DashboardPage() {
  const {lang}=useI18n();const c=copy[lang]
  const [company, setCompany] = useState<CompanyRow | null>(null);const [opportunities, setOpportunities] = useState<Opportunity[]>([]);const [pipeline, setPipeline] = useState<PipelineRow[]>([]);const [loading, setLoading] = useState(true)
  useEffect(() => { async function load() { const { data: auth } = await supabase.auth.getUser(); const user=auth.user; if(!user)return; const [{data:companyData},{data:oppData},{data:pipelineData}]=await Promise.all([supabase.from('companies').select('*').eq('owner_id',user.id).order('created_at',{ascending:true}).limit(1).maybeSingle(),supabase.from('opportunities').select('*').eq('region','Sarawak').order('closing_date',{ascending:false,nullsFirst:false}),supabase.from('pipeline_items').select('id,opportunity_id,stage,deal_value').eq('user_id',user.id)]); setCompany((companyData as CompanyRow|null)??null); setOpportunities((oppData as Opportunity[]|null)??[]); setPipeline((pipelineData as PipelineRow[]|null)??[]); setLoading(false)} load() },[])
  const matches=useMemo(()=>!company?[]:opportunities.map(o=>({opportunity:o,match:matchOpportunity(o,company)})).filter(x=>x.match.score>0).sort((a,b)=>b.match.score-a.match.score||String(b.opportunity.closing_date).localeCompare(String(a.opportunity.closing_date))),[company,opportunities])
  const savedIds=new Set(pipeline.map(p=>p.opportunity_id).filter(Boolean)); const won=pipeline.filter(p=>p.stage==='Won'); const generated=won.reduce((s,p)=>s+Number(p.deal_value??0),0)
  async function saveOpportunity(id:string){const {data:auth}=await supabase.auth.getUser();if(!auth.user||savedIds.has(id))return;const {data}=await supabase.from('pipeline_items').insert({user_id:auth.user.id,opportunity_id:id,stage:'New',currency:'MYR',verified:false}).select('id,opportunity_id,stage,deal_value').single();if(data)setPipeline(v=>[...v,data as PipelineRow])}
  return <MemberShell><main className="member-page"><div className="container"><div className="member-heading"><div><div className="eyebrow">{c.eyebrow}</div><h1 className="page-title">{company?`${company.name} · ${c.suffix}`:c.title}</h1><p className="sub">{c.sub}</p></div><Link className="btn" href="/profile">{c.edit}</Link></div>{loading?<div className="panel">{c.loading}</div>:!company?<div className="empty-state"><h2>{c.finish}</h2><p>{c.finishText}</p><Link className="btn primary" href="/profile">{c.complete}</Link></div>:<><div className="kpis member-kpis"><div className="kpi"><strong>{matches.length}</strong><span>{c.matches}</span></div><div className="kpi"><strong>{matches.filter(x=>x.match.score>=70).length}</strong><span>{c.high}</span></div><div className="kpi"><strong>{pipeline.length}</strong><span>{c.saved}</span></div><div className="kpi"><strong>RM{generated.toLocaleString()}</strong><span>{c.won}</span></div></div><section className="section compact"><div className="section-head"><div><div className="eyebrow">{c.section}</div><h2>{c.recommended}</h2></div><Link className="source" href="/opportunities">{c.browse} →</Link></div>{matches.length===0?<div className="empty-state"><h2>{c.none}</h2><p>{c.noneText}</p></div>:<div className="grid">{matches.slice(0,9).map(({opportunity:o,match})=><article className="card opportunity-card" key={o.id}><div className="score-row"><span className="match-score">{match.score}% {c.profileMatch}</span><span className="status-dot">{c.official}</span></div><div className="eyebrow">Sarawak · {o.opportunity_type}</div><Link href={`/opportunities/${o.id}`} className="title link-title">{o.title}</Link><div className="meta">{o.buyer}<br/>{c.closing} {o.closing_date??'—'}</div><div className="card-actions"><Link className="btn small" href={`/opportunities/${o.id}`}>{c.view}</Link><button className="btn small primary" disabled={savedIds.has(o.id)} onClick={()=>saveOpportunity(o.id)}>{savedIds.has(o.id)?c.savedButton:c.save}</button></div></article>)}</div>}</section></>}</div></main></MemberShell>
}
