'use client'
import Link from 'next/link'
import PublicHeader from '@/components/public-header'
import SiteFooter from '@/components/site-footer'
import {useI18n} from '@/components/i18n'

const copy={
 en:{eyebrow:'Trust & Legal',title:'How Borneo Business handles information',intro:'Borneo Business is an independent business intelligence platform. We organize public information to make opportunities easier to discover and understand, while keeping the original source authoritative.',principles:[['Independent','Not a government agency and not endorsed by one.'],['Source-led','Critical procurement details should be verified at the original source.'],['Correctable','Users can report inaccurate or outdated information for review.']],view:'View policy',items:[['/trust/data-sources','Data Sources','Where our opportunity and market information comes from.'],['/trust/data-accuracy','Data Accuracy','How we handle verification, updates and corrections.'],['/trust/translation','Translation Notice','How machine-assisted translation and shared caching work.'],['/legal/privacy','Privacy','How account, company and product-use data is handled.'],['/legal/disclaimer','Disclaimer','Important limits on procurement and business information.'],['/legal/third-party','Third-Party & IP','External services, source ownership and intellectual property.']]},
 zh:{eyebrow:'信任与法律',title:'Borneo Business 如何处理信息',intro:'Borneo Business 是独立商业情报平台。我们整理公开信息，让商机更容易被发现和理解，同时始终保留原始来源的权威性。',principles:[['独立平台','不是政府机构，也不代表任何政府机构。'],['以来源为核心','关键采购要求应始终回到原始来源核实。'],['可以更正','用户可以举报错误或过时信息，由平台进行审核。']],view:'查看政策',items:[['/trust/data-sources','数据来源','了解我们的商机与市场信息来自哪里。'],['/trust/data-accuracy','数据准确性','了解我们如何处理核实、更新与更正。'],['/trust/translation','翻译说明','了解机器辅助翻译与共用缓存如何运作。'],['/legal/privacy','隐私政策','了解账户、公司与产品使用数据如何处理。'],['/legal/disclaimer','免责声明','了解采购与商业信息的重要责任范围。'],['/legal/third-party','第三方与知识产权','了解外部服务、来源权利与知识产权。']]},
 ms:{eyebrow:'Kepercayaan & Undang-undang',title:'Cara Borneo Business mengendalikan maklumat',intro:'Borneo Business ialah platform risikan perniagaan bebas. Kami menyusun maklumat awam supaya peluang lebih mudah ditemui dan difahami sambil mengekalkan sumber asal sebagai rujukan berkuasa.',principles:[['Bebas','Bukan agensi kerajaan dan tidak disokong oleh mana-mana agensi.'],['Berpandukan sumber','Butiran perolehan penting hendaklah disahkan pada sumber asal.'],['Boleh dibetulkan','Pengguna boleh melaporkan maklumat salah atau lapuk untuk semakan.']],view:'Lihat dasar',items:[['/trust/data-sources','Sumber Data','Dari mana maklumat peluang dan pasaran kami diperoleh.'],['/trust/data-accuracy','Ketepatan Data','Cara kami mengendalikan pengesahan, kemas kini dan pembetulan.'],['/trust/translation','Notis Terjemahan','Cara terjemahan bantuan mesin dan cache kongsi berfungsi.'],['/legal/privacy','Privasi','Cara data akaun, syarikat dan penggunaan produk dikendalikan.'],['/legal/disclaimer','Penafian','Had penting bagi maklumat perolehan dan perniagaan.'],['/legal/third-party','Pihak Ketiga & IP','Perkhidmatan luar, pemilikan sumber dan harta intelek.']]}
} as const

export default function Trust(){const {lang}=useI18n();const c=copy[lang];return <><PublicHeader/><main className="section"><div className="container policy-container"><div className="eyebrow">{c.eyebrow}</div><h1>{c.title}</h1><p className="lead policy-lead">{c.intro}</p><div className="trust-principles">{c.principles.map(p=><div key={p[0]}><strong>{p[0]}</strong><span>{p[1]}</span></div>)}</div><div className="trust-list">{c.items.map(i=><Link href={i[0]} key={i[0]}><div><strong>{i[1]}</strong><p>{i[2]}</p></div><span>{c.view} →</span></Link>)}</div></div></main><SiteFooter/></>}
